### ISSUE TITLE
Custom transformation rules do not apply

### ISSUE THREAD

**Issue by rivermartinez** [Automattic/fb-instant-articles#1005]
## Steps required to reproduce the problem

1. I have "enable custom transformer rule" with code:

`
{  
   "rules":[  
      {  
         "class":"BlockquoteRule",
         "selector":"blockquote"
      },
      {  
         "class":"ParagraphRule",
         "selector":"p"
      },
      {  
         "class":"H2Rule",
         "selector":"h2"
      },
      {  
         "class":"H1Rule",
         "selector":"h1"
      },
      {  
         "class":"ListElementRule",
         "selector":"ol, ul"
      },
      {  
         "class":"ListItemRule",
         "selector":"li"
      },
      {  
         "class":"AnchorRule",
         "selector":"a",
         "properties":{  
            "anchor.href":{  
               "attribute":"href",
               "selector":"a",
               "type":"string"
            }
         }
      },
      {  
         "class":"ItalicRule",
         "selector":"i"
      },
      {  
         "class":"EmphasizedRule",
         "selector":"em"
      },
      {  
         "class":"BoldRule",
         "selector":"b, strong"
      },
      {  
         "class":"ImageRule",
         "selector":"img",
         "properties":{  
            "image.url":{  
               "attribute":"src",
               "selector":"img",
               "type":"string"
            },
            "image.caption":{  
               "attribute":"src",
               "selector":"img",
               "type":"element"
            }
         }
      },
      {  
         "class":"ImageRule",
         "selector":"figure",
         "properties":{  
            "image.url":{  
               "attribute":"src",
               "selector":"img",
               "type":"string"
            },
            "image.caption":{  
               "selector":"p.wp-caption-text,footer",
               "type":"element"
            }
         }
      },
      {  
         "class":"H2Rule",
         "selector":"h2,h3,h4"
      }
   ]
}
`

The sharing debug https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fwww.laprensa.com.ni%2F2018%2F12%2F28%2Fpolitica%2F2508899-daniel-ortega-a-las-puertas-de-enfrentar-en-la-oea-a-la-carta-democratica-interamericana response on ia:markup_url the url https://www.laprensa.com.ni/2018/12/28/politica/2508899-daniel-ortega-a-las-puertas-de-enfrentar-en-la-oea-a-la-carta-democratica-interamericana?ia_markup=1

## Expected Result
In the author should show "Lucía Nava, Judith Flores" this data comes from a custom field, it is not the true author of the note

## Actual Result 
In the author shows "Cindy Fuller", this is the true author (who created the post) of the post

## Version Info

* Plugin version: 4.2.0
* WordPress version: 4.9
* PHP version: 5.6.30

**Comment by pestevez** [comment]
Hi @rivermartinez - I don't think this is related to the rules but to the way the plugin is implemented. Commit f92aa00d83faaa349cc5ba1e45357bf92fe2eab2 may give you some info around how to use a hook to customize the author that you want.

This seems related to #505.
