### ISSUE TITLE
Updating failed with the Gutenberg editor

### ISSUE THREAD

**Issue by ericvalois** [Automattic/fb-instant-articles#1009]
## Steps required to reproduce the problem

1. Trying to edit a pre-published post with the new editor throws an "Updating failed" error on save.

## Expected Result
It should not display an error. 

## Version Info

* Plugin version: 4.2.0
* WordPress version: 5.0.3
* PHP version: 7.1

It is tested on Twenty Nineteen with only Instant Articles for WP.
![screen shot 2019-01-10 at 10 40 25 am](https://user-images.githubusercontent.com/7623388/50979635-e6cf4680-14c4-11e9-8025-16200818dc6e.png)

**Comment by elliotfern** [comment]
@ericvalois I have the same issue and I don't use the Twenty Nineteen theme, which means that the plugin crash with all themes. Does anyone else have the same issue?

**Comment by pdobrescu** [comment]
Hello. Having the same issue on WordPress 5.2.2, PHP 7.3.6 and plugin version 4.2.0. As soon as the plugin is deactivated, the issue is gone. The good thing though is that the posts seem to be correctly updated/published.
