### ISSUE TITLE
Instant Articles Production Feed not updating

### ISSUE THREAD

**Issue by Wizardftr** [Automattic/fb-instant-articles#1017]
## Steps required to reproduce the problem
1. Publish post in WP site

## Actual Result
No errors and no warning reported on my WP site.

The plugin on my WP site says:
"This post will be available as an Instant Article.
This post was transformed into an Instant Article with no warnings"

But post is not submitted to Production Articles (if you check the attachment you can see that the last post converted to Instant Article was on 02/01/2019 which is two weeks ago )

I have attached attached two screenshots 
- Production Articles Feed where you can see that posts that are converted to Instant Articles
- Production RSS Feed section which shows an error but im not using RSS feed since i have been converting my Articles with API

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.2.0
* WordPress version: 5.0.3
* PHP version: 7.1

Without the above information we are not able to debug the issue and will close it.

**Comment by Wizardftr** [comment]
![production articles -last updated](https://user-images.githubusercontent.com/10176063/52827958-1f1b0380-30c7-11e9-8596-ee39c7e9e152.png)
![production rss feed - error](https://user-images.githubusercontent.com/10176063/52827959-1f1b0380-30c7-11e9-9db5-08c2fa036a31.png)

**Comment by mdkaleem02** [comment]
Same problem.

**Comment by Aiwatech** [comment]
I have same problem, please help ...
