### ISSUE TITLE
H2 header is repeating the first paragraph of the articles, how to disable it?

### ISSUE THREAD

**Issue by beeriz** [Automattic/fb-instant-articles#1028]
Hi, thanks for reading.

## Steps required to reproduce the problem & Actual Result 
When publishing an article, our first paragraph (p) is also showing as a subtitle (h2) under the title of the article, making it really annoying for the readers.

## Expected Result
No H2 header showing on the article when no H2 tag is used.

## AI Markup
https://pastebin.com/A3yk8j6W 

## Version Info
* Plugin version: 4.2.0
* WordPress version: 5.2
* PHP version: 7.3

Any idea how to disable the H2 subtitle, until a permanent fix?

**Comment by 9bagel** [comment]
I have the same problem. Is there any solution?
