### ISSUE TITLE
I am getting minimal readership error while trying to submit my website URL 

### ISSUE THREAD

**Issue by incendies** [Automattic/fb-instant-articles#1029]
I am getting this error (The provided URL is not being accepted because the site has minimal readership) while trying to submit my website URL: https://chaospin.com 

Can you help me, please?

**Comment by jerclarke** [comment]
You are screwed. There's no way to fix this other than magically getting your site to have more than the unstated minimum readership to qualify. 

This plugin has wasted your time. 

This is a bug. The plugin should help you check you qualify in terms of readership before encouraging you to continue with setup.
