### ISSUE TITLE
You've Lost Access to Monetization

### ISSUE THREAD

**Issue by meaakashpatil** [Automattic/fb-instant-articles#1033]
You've Lost Access to Monetization 

I am trying 3 to 4 time appeal and befor appeal solve some errors by my side. but still my instant article is lost and any time Show this same msg👇. 
and i don't the exactly Which Reason still my instant article is lost..
plz help me🙏

Thanks for submitting an appeal. After taking a look, we've confirmed that your Page isn't eligible for monetization at this time because at least one of your Instant Articles website domains has missing or incomplete sections.

In order for your Page to become eligible for monetization, make sure your Instant Articles domains correctly load. Learn more about our policies for Instant Articles: 

https://developers.facebook.com/docs/instant-articles/policy

Once you've addressed this issue, you can submit another appeal in 7 days.

Visit the Help Center to review our Monetization Eligibility Standards:

https://www.facebook.com/help/publisher/monetization-eligibility

Learn more about our guidelines for monetizing content:

https://www.facebook.com/help/publisher/content-guidelines
Thanks,

Version Info

instant article plugin:  4.2.0
WordPress version: 5.2.3
PHP version: 7.2.22

so many time I try appeals but still my instant is lost and not find exactly reason.. plz help me🙏

**Comment by Samar37** [comment]
Hi Aakash
Did you got the solution of your problem
