### ISSUE TITLE
URGENT! error when updating a post

### ISSUE THREAD

**Issue by notPradip** [Automattic/fb-instant-articles#1035]
Need some urgent help lad, this error below comes up every time im updating a post not when publishing a new one. Any idea how to fix this, please?

#0 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
#4 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(366): Facebook\Facebook->sendRequest('POST', '/?id=https%3A%2...', Array, '9f0d52f0408f0de...', NULL, 'v2.10')
#6 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(518): Facebook\Facebook->post('/?id=https%3A%2...', Array, '9f0d52f0408f0de...')
#7 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-includes/class-wp-hook.php(286): invalidate_scrape_on_update(17954, Object(WP_Post), Object(WP_Post))
#8 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#9 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#10 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-includes/post.php(3925): do_action('post_updated', 17954, Object(WP_Post), Object(WP_Post))
#11 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-includes/post.php(4028): wp_insert_post(Array, false)
#12 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-admin/includes/post.php(405): wp_update_post(Array)
#13 /home/sites/2a/c/xxxxxxxxxx/public_html/wp-admin/post.php(218): edit_post()
#14 {main}

Attached are the installed Plugin 
![image](https://user-images.githubusercontent.com/18046492/66255367-492e4c80-e7a2-11e9-8d1f-c1dd2f7b5ba8.png)

**Comment by WesleyCarnicle** [comment]
I get the same message
