### ISSUE TITLE
Anyone experience this kind of problem? &NewLine 

### ISSUE THREAD

**Issue by brianvienn** [Automattic/fb-instant-articles#1036]
## Steps required to reproduce the problem

1. No content converted to IA
2. Article converted to "<p>&NewLine;&NewLine;</p>"
3. 

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: Version 4.2.0
* WordPress version: WordPress 5.2.4
* PHP version: 
![prob2](https://user-images.githubusercontent.com/56676064/67736265-f9aa0c00-fa41-11e9-936e-4090b42bb1e6.JPG)
![prob1](https://user-images.githubusercontent.com/56676064/67736266-fa42a280-fa41-11e9-8aae-432735e61b1f.JPG)

Without the above information we are not able to debug the issue and will close it.

**Comment by amananjaan** [comment]
i faced Similar But I am using Blogger, My Any Update from today is not Showing In Production Article

**Comment by brianvienn** [comment]
How did you fix the &NewLine?


"Robb"
Vienn Brian B. Mejino

*New Media* - Platform Technical Supervisor
0915-641-5585
+632-687-6181 loc.662

**Comment by amananjaan** [comment]
Nope There is Something Wrong with facebook, I talked with team they said they will Fix soon and Their Soon won't come soon So i Created Instant Article Manually...

**Comment by brianvienn** [comment]
really? i'm doing it manually right now? do you have facebook? Can i add
you?


"Robb"
Vienn Brian B. Mejino

*New Media* - Platform Technical Supervisor
0915-641-5585
+632-687-6181 loc.662

**Comment by amananjaan** [comment]
Yes Amanpreet Khanuja
