### ISSUE TITLE
How To fix No rules defined for <div class="epvc-post-count"> in the context of InstantArticle

### ISSUE THREAD

**Issue by aloneindians** [Automattic/fb-instant-articles#1039]
![image](https://user-images.githubusercontent.com/53474335/71518561-84d83e80-28d9-11ea-8836-0c6d1ff31edc.png)

**Comment by aloneindians** [comment]
any one can reply on this please help

**Comment by kampit** [comment]
Publishing settings -> Custom transfer rules -> Tick (Enable custom transformer rules)

```
{ "rules" :[
{ "class": "PassThroughRule", "selector" : "div.epvc-post-count" }
]}
```
