### ISSUE TITLE
Issue When Publishing A Post 

### ISSUE THREAD

**Issue by WesleyCarnicle** [Automattic/fb-instant-articles#1040]
#0 /home/searkwea/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /home/searkwea/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home/searkwea/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home/searkwea/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 0, Array)
#4 /home/searkwea/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /home/searkwea/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(366): Facebook\Facebook->sendRequest('POST', '/?id=http%3A%2F...', Array, 'EAAHqUBa8lKMBAL...', NULL, 'v2.10')
#6 /home//public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(518): Facebook\Facebook->post('/?id=http%3A%2F...', Array, 'EAAHqUBa8lKMBAL...')
#7 /home//public_html/wp-includes/class-wp-hook.php(288): invalidate_scrape_on_update(24619, Object(WP_Post), Object(WP_Post))
#8 /home//public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(24621, Array)
#9 /home//public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#10 /home//public_html/wp-includes/post.php(4094): do_action('post_updated', 24619, Object(WP_Post), Object(WP_Post))
#11 /home//public_html/wp-includes/post.php(4197): wp_insert_post(Array, false)
#12 /home//public_html/wp-admin/includes/post.php(407): wp_update_post(Array)
#13 /home//public_html/wp-admin/post.php(219): edit_post()
#14 {main}
## Steps required to reproduce the problem

1. 
2. 
3. 

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 
* WordPress version: 
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by andresmorat** [comment]
Hi, I also have the same problem when I do quick editing on an entry.
I have reviewed the entry and exit code and it contains no warnings.

I copy the error shown here:

#0 /var/www/html_new/wp/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /var/www/html_new/wp/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /var/www/html_new/wp/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /var/www/html_new/wp/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
#4 /var/www/html_new/wp/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /var/www/html_new/wp/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(361): Facebook\Facebook->sendRequest('POST', '/?id=https%3A%2...', Array, 'EAAJI9wJRpdUBAF...', NULL, 'v2.10')
#6 /var/www/html_new/wp/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(518): Facebook\Facebook->post('/?id=https%3A%2...', Array, 'EAAJI9wJRpdUBAF...')
#7 /var/www/html_new/wp/wp-includes/class-wp-hook.php(288): invalidate_scrape_on_update(122582, Object(WP_Post), Object(WP_Post))
#8 /var/www/html_new/wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#9 /var/www/html_new/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#10 /var/www/html_new/wp/wp-includes/post.php(4094): do_action('post_updated', 122582, Object(WP_Post), Object(WP_Post))
#11 /var/www/html_new/wp/wp-includes/post.php(4197): wp_insert_post(Array, false)
#12 /var/www/html_new/wp/wp-admin/includes/post.php(407): wp_update_post(Array)
#13 /var/www/html_new/wp/wp-admin/includes/ajax-actions.php(2062): edit_post()
#14 /var/www/html_new/wp/wp-includes/class-wp-hook.php(288): wp_ajax_inline_save('')
#15 /var/www/html_new/wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#16 /var/www/html_new/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#17 /var/www/html_new/wp/wp-admin/admin-ajax.php(175): do_action('wp_ajax_inline-...')
#18 {main}

**Comment by diegoquinteiro** [comment]
Hi @WesleyCarnicle and @andresmorat - can you double check if your settings are valid for App ID, App Secret and Access token? Also, can you try to reproduce the issue again to rule out a temporary server-side error?

Also, where is the error you've pasted is shown: in the UI or in the logs?

For the access token, you can check if it's still valid on the Token debugger: https://developers.facebook.com/tools/debug/accesstoken/

**Comment by mehrabhosain** [comment]
#0 /home/channelionline/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /home/channelionline/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home/channelionline/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home/channelionline/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
#4 /home/channelionline/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /home/channelionline/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(361): Facebook\Facebook->sendRequest('POST', '/?id=https%3A%2...', Array, 'bf5464cc1d7532f...', NULL, 'v2.10')
#6 /home/channelionline/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(518): Facebook\Facebook->post('/?id=https%3A%2...', Array, 'bf5464cc1d7532f...')
#7 /home/channelionline/public_html/wp-includes/class-wp-hook.php(303): invalidate_scrape_on_update(816904, Object(WP_Post), Object(WP_Post))
#8 /home/channelionline/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(817073, Array)
#9 /home/channelionline/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#10 /home/channelionline/public_html/wp-includes/post.php(4442): do_action('post_updated', 816904, Object(WP_Post), Object(WP_Post))
#11 /home/channelionline/public_html/wp-includes/post.php(4570): wp_insert_post(Array, false, true)
#12 /home/channelionline/public_html/wp-admin/includes/post.php(423): wp_update_post(Array)
#13 /home/channelionline/public_html/wp-admin/post.php(227): edit_post()
#14 {main}

**Comment by GaryJones** [comment]
Closing for lack of feedback.
