### ISSUE TITLE
Receiving wrong source/medium on Google Analytics

### ISSUE THREAD

**Issue by abazeed** [Automattic/fb-instant-articles#1048]
## Steps required to reproduce the problem

1. Apply the following setup:
* Article Style: not the default one
* Facebook Page ID
* Copyright
* Right-to-Left Publishing
* Ad Type: Facebook Audience Network
* Ad Dimensions: Large
* Analytics: Embed code
```html
<script async="async" src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXXX-X"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments)};
  gtag('js', new Date());
  gtag('set', 'page_title', 'FBIA: ' + ia_document.title);
  gtag('set', 'campaignSource', 'Facebook');
  gtag('set', 'campaignMedium', 'Instant Article');
  gtag('set', { referrer: ia_document.referrer });
  gtag('config', 'UA-XXXXXXXX-X');
</script>
```
* Enable custom transformer rules
```json
{"rules": [
    {"class": "IgnoreRule", "selector": "meta"},
    {"class": "PassThroughRule", "selector": "div.jeg_meta_author"}
]}
```
2. All the settings which are not listed above are not active/checked

## Expected Result

Receiving hits from my Instant Articles on GA with the following UTM values:
* Campaign Source: Facebook
* Campaign Medium: Instant Article

## Actual Result 
I'm receiving hits from my Instant Articles in GA, but the source/medium is:
* Campaign Source: (direct)
* Campaign Medium: (none)

The page title is received properly.

## Version Info

* Plugin version: 4.2.0
* WordPress version: 5.4 Multisite
* PHP version: 7.2.26

**Comment by Zigmundadu** [comment]
@abazeed did you solve the problem? I have the same problem with a Multisite (subdirectories).
Site A has Source Facebook and Medium Social
when I click on Site B of the same Multisite the Source become direct and medium none

**Comment by pratikhjoshi** [comment]
I am facing the same issue, I have implemented this set up in instant article in September. Data seems good in October and November but since January my direct traffic increasing like a hell and instant article traffic went down. 

I am sure that Facebook is not reading campaign source medium and sending those numbers in direct channel. Still finding the solutions but no SUCCESS. Please help is anyone can share the solution on it. 

thank you

**Comment by abazeed** [comment]
> @abazeed did you solve the problem? I have the same problem with a Multisite (subdirectories). Site A has Source Facebook and Medium Social when I click on Site B of the same Multisite the Source become direct and medium none

@Zigmundadu, @pratikhjoshi, I stopped using the official IA plugin of Facebook because it's no more maintained! I'm currently using this plugin [WP Native Articles](https://wp-native-articles.com/) which is recommended by [Kinsta](https://kinsta.com/blog/facebook-instant-articles/).

Another good option that supports Google AMP and PWA besides Facebook IA is [Instantify](https://codecanyon.net/item/instantify-progressive-web-apps-google-amp-facebook-instant-articles-for-wordpress/25757693). You can buy it from [here](https://www.gplplus.com/product/instantify-wordpress-plugin-pwa-google-amp-facebook-ia/) for 4.99$.
