### ISSUE TITLE
YouTube embed not working in FIA

### ISSUE THREAD

**Issue by amitmalewar** [Automattic/fb-instant-articles#1052]
## Steps required to reproduce the problem

1. Create post using block editor
2. Add Video from Youtube using Youtube block

## Expected Result
FIA should display a YouTube embed.

## Error
`Invalid selector for fields (image.url). The node being transformed was <figure> in the context of InstantArticle within the Rule ImageRule with these properties: { image.url=StringGetter}
`
## Version Info
Latest Version

* Plugin version: 4.2.1
* WordPress version: 5.4.2
* PHP version: 7.3

**Comment by ixnaypt** [comment]
Exact same behavior here.

**Comment by danielbachhuber** [comment]
@amitmalewar @ixnaypt Were either of you able to work out a solution for this?

**Comment by ixnaypt** [comment]
Not at all @danielbachhuber :(

**Comment by amitmalewar** [comment]
@danielbachhuber  @ixnaypt For now, consider using Classic block to embed YouTube video. This will help.

**Comment by ixnaypt** [comment]
Thanks @amitmalewar, will try and let you know. But have you guys been able to reproduce this in order to deploy a fix?

**Comment by keyinora** [comment]
Wrote the following rule, till this can be fixed in the plugin itself

{
    "rules": [{
        "class": "PassThroughRule",
        "selector": "figure.wp-block-embed-youtube"
    }, {
    	"class": "PassThroughRule",
    	"selector": "div.wp-block-embed__wrapper" 
    }]
}
