### ISSUE TITLE
old articles are uploaded to facebook and published

### ISSUE THREAD

**Issue by lubimow** [Automattic/fb-instant-articles#1054]
I have installed your plugin. In the settings in facebook, I set to download from feed and save as drafts.
In the section "public articles" old materials, which are more than a year old, began to appear (they could not be in the feed). Moreover, these old articles have the status of "published", although I did not approve them for publication.
How to make sure that all articles were in the "unpublished" status and they were published only with my permission.

* Plugin version: 4.2.1
* WordPress version: 5.4.2
* PHP version: 7.3

**Comment by amgmbs** [comment]
I think the feed is ordered by last modified
