### ISSUE TITLE
Instagram Embed - 429 Too Many Requests

### ISSUE THREAD

**Issue by awongwork** [Automattic/fb-instant-articles#1067]
## Steps required to reproduce the problem

1. Add instagram embed via a URL
2. Publish the post
3. Visit the post on the website in a web browser (not in the FB app)

## Expected Result
IG embed renders properly without the FBIA plugin interfering.

## Actual Result 
IG embed does in fact render properly, but the API error  `429 Too Many Requests` is observed in Query Monitor.
![image](https://user-images.githubusercontent.com/4719921/101182778-8dbead80-361c-11eb-9815-ef91391d6f29.png)
Since we are visiting the post as a regular page and not as FBIA, the filter `instant_articles_embed_oembed_html` should not have been triggered? 

## Version Info

* Plugin version: 4.0.5 
* WordPress version: 5.5.2
* PHP version: version used in VIP GO

Without the above information we are not able to debug the issue and will close it.

**Comment by gisedaye** [comment]
I'm not able to reproduce the issue, as IG URL embeds for WordPress don't work anymore. Using th embed code provided on IG posts seems to work ok.
Could you please try again using the embed code?

**Comment by GaryJones** [comment]
Fixed in #1076.
