### ISSUE TITLE
/feed/instant-articles doesn't work in my domain

### ISSUE THREAD

**Issue by yannnaingoo** [Automattic/fb-instant-articles#1070]
## Steps required to reproduce the problem

1. wordpress 5.6
2. 
3. 

## Expected Result
rss feed link errors 

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.2.1
* WordPress version: 5.6
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by gisedaye** [comment]
@yannnaingoo could you please send us more info? What error are you getting? Did you connect the RSS feed to your FB page in Creator Studio?
