### ISSUE TITLE
<Figurecaption> Not working or showing up on Instant Article

### ISSUE THREAD

**Issue by Drake2277** [Automattic/fb-instant-articles#1072]
Hi everyone,

I use captions on pictures in WordPress website. Here's an example: https://ibb.co/Nn2gS9N

When Facebook transform it into an Instant article, it the captions doesn't show up on Instant article, it looks like this: https://ibb.co/86T7chF

As you can see, the caption is missing in my instant article, and in wordpress it keep giving me this error: https://ibb.co/g63Gxd5

Can anyone help me with the issue?

Many Thanks.

**Comment by gisedaye** [comment]
Hi @Drake2277, could you please provide more info?
figcaption is [currently supported on IA](https://developers.facebook.com/docs/instant-articles/reference/caption) 
It would be helpful to see how your html code looks like, to understand why the wordpress plugin is throwing those warnings.

Thanks!

**Comment by samborcia** [comment]
I'm also having this same exact issue.

**Comment by GaryJones** [comment]
Closing for lack of feedback.
