### ISSUE TITLE
Is this plugin abandoned?

### ISSUE THREAD

**Issue by justinmaurerdotdev** [Automattic/fb-instant-articles#1081]
There are months of unanswered issues here and on [wordpress.org](https://wordpress.org/support/plugin/fb-instant-articles/). In that time, Facebook's Creator Studio has pushed a new interface to some users, but not others. I won't list the issues I ran into trying to set this up, because there are already support requests for most of them. 

Could we please get an update on whether we're likely to see these issues addressed? If not, people will likely need to roll their own Instant Articles solutions, rather than spend time fussing with this broken plugin.

**Comment by terrapop** [comment]
100% agree.

**Comment by GaryJones** [comment]
To be clear - Meta (Facebook) is no longer maintaining this plugin, and Automattic won't be maintaining it either. We'll do a final release to add in PHP 8 compatibility to give users some breathing room, but at this point in the product lifecycle, publishers should be advised to stop using this plugin and instead use direct site traffic for Facebook content.
