### ISSUE TITLE
RSS Feed not showing properly after updating to PHP 8.0.x

### ISSUE THREAD

**Issue by kiranrs** [Automattic/fb-instant-articles#1087]
## Steps required to reproduce the problem

1. Install WordPress and Instant Articles for WP then configure.
2. Goto RSS feed

## Expected Result
[RSS 2.0 feed optimized for Instant Articles](https://developers.facebook.com/docs/instant-articles/publishing/setup-rss-feed/)

## Actual Result 
RSS feed breaks after some lines. Not showing completely.

## Version Info

* Plugin version: 4.2.1
* WordPress version: 5.8.3
* PHP version: 8.0.12

**Comment by fahedyasin** [comment]
Hi. any update on this one?

**Comment by GaryJones** [comment]
There's not enough info here to begin debugging. What was the source content of the feed item where it broke? Can you reproduce with the latest release (right now it's 5.0.0-RC)? Are there any PHP error messages in logs to indicate what happened?
