### ISSUE TITLE
Add audio tag in my instant article Feed

### ISSUE THREAD

**Issue by sandeepavasthi01** [Automattic/fb-instant-articles#1090]
Hi,

We have used this plugin for Facebook instant articles. I want to add <audio> file in our content of instant article feed of **Podcast** custom post type. 

 * Example:
 *    <audio>
 *       <source src="http://foo.com/mp3"> 
 *    </audio

Is this possible? How can we achieve this? 

**Please help?**

**Comment by gabadedibu** [comment]
i tried it on ([https://dramaplug.com](https://dramaplug.com))it was bouncing back .
