### ISSUE TITLE
Uncaught exception 'InvalidArgumentException' in Validators/Type.php:183

### ISSUE THREAD

**Issue by sandeepavasthi01** [Automattic/fb-instant-articles#1091]
## Steps required to reproduce the problem

1. 
2. 
3. 

## Expected Result
No error message

## Actual Result 

> Error Message Uncaught exception 'InvalidArgumentException' with message 'Method expects this value ----[ bool(false) ]---- to be one of the types ====[ string(6) "STRING" ]====' in /var/www/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Validators/Type.php:183 …ook-instant-articles-sdk-php/src/Facebook/InstantArticles/Validators/Type.php (70) …ook-instant-articles-sdk-php/src/Facebook/InstantArticles/Validators/Type.php (39) …ant-articles-sdk-php/src/Facebook/InstantArticles/Elements/InstantArticle.php (133) …ar/www/wp-content/plugins/fb-instant-articles/class-instant-articles-post.php (677) …/var/www/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php (386)

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 
* WordPress version: 
* PHP version: 

Without the above information we are not able to debug the issue and will close it.

**Comment by GaryJones** [comment]
Without some indication of versions and content and what we could do to reproduce this, it's inactionable.

Closing for now.
