### ISSUE TITLE
Error trace printed on screen

### ISSUE THREAD

**Issue by manuelRod** [Automattic/fb-instant-articles#1114]
## Steps required to reproduce the problem
I know the plugin has discontinued maintenance, but it would be good to be solved.

1. When I update a post in my local environment or staging (wrong token id), the error trace is printed on the screen. The exception is captured but not handled properly.
2. Admin notices are not shown.
3. There is debugging code left in master/latest stable version ( see: https://github.com/Automattic/fb-instant-articles/blob/master/facebook-instant-articles.php#L529)
4. I see develop branch has fixed the problem, besides admin notices being also declared outside the function.
See:
![Screen Shot 2023-01-19 at 5 57 51 PM](https://user-images.githubusercontent.com/1736736/213509515-60a306b6-267d-4f91-b510-bdfec614a435.png)
p.s: Is Develop a stable version? can it be used?

## Expected Result
No errors on the screen.

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 5.0.2
* WordPress version: 6.2
* PHP version: 8.0

Without the above information we are not able to debug the issue and will close it.

**Comment by GaryJones** [comment]
Hi @manuelRod,

As this plugin is discontinued, and as Facebook is stopping support for FBIA articles anyway, the issue you reported isn't going to be fixed. You could make the change in your own plugin code or not use the wrong token ID.

> p.s: Is Develop a stable version? can it be used?

`develop` has got [these extra changes](https://github.com/Automattic/fb-instant-articles/milestone/25?closed=1) in. They should be stable, but you'd need to test.
