### ISSUE TITLE
Attach Embed-Code at the end of IA content unescaped

### ISSUE THREAD

**Issue by withoutfield** [Automattic/fb-instant-articles#158]
I use Custom Fields for Youtube Video Links witch I render via oEmbed in my Article. I want these embeds also in the IA-Feed and I tried to insert them like this:

```
add_action( 'instant_articles_after_transform_post', function ($ia_post) {
    $instant_article = $ia_post->instant_article;
    $post_id = $ia_post->get_the_id();
    $video_url = get_post_meta( $post_id, 'tf_medialink_enable', true );
    $video_url = '<figure class="op-social">' . wp_oembed_get( $video_url ) . '</figure>';
    $instant_article->addChild( Paragraph::create()->appendText($video_url) );

} );
```

This works well but the Code is escaped: 

`<p>&lt;figure class="op-social"&gt;&lt;iframe width="1200" height="675" src="https://www.youtube.com/embed/Ew8frW54XGU?feature=oembed" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;&lt;/figure&gt;</p>`

Any Idea how to become the unescaped Code?

**Comment by philipjohn** [comment]
The best way to use oEmbeds with the plugin is to rely on WP's own oEmbed functionality, which the plugin handles and converts to the appropriate markup.

To do that, you'll need to insert the YouTube URL into the content at the right point, *before* the FBIA plugin grabs that content and converts it to FBIA-compatible markup.
