### ISSUE TITLE
Feature request: Status indicator column in Posts list

### ISSUE THREAD

**Issue by schneidan** [Automattic/fb-instant-articles#165]
Would be neat if there were, say, a set of status codes or red/yellow/green indicator icons in a separate column in the Posts list that indicated the IA status of a story -- maybe Red for not submitted, not processed; yellow for an issue; green for successfully submitted and no errors. Perhaps a tooltip on hover could give more details, particularly about the errors on a yellow status.

Just an idea.

**Comment by philipjohn** [comment]
Nice idea! We should definitely do this if we can.
