### ISSUE TITLE
Ability to control whether a post should be published as an Instant Article

### ISSUE THREAD

**Issue by demoive** [Automattic/fb-instant-articles#186]
There should be the ability to control whether an individual posts/pages should be pushed to Facebook as an Instant Article. Suggestions include:
- Using tags/categories as the condition
- Dedicated UI on each post/page

References:
https://wordpress.org/support/topic/limitexclude-articles-by-category
https://wordpress.org/support/topic/polldaddy-embeds-being-stripped
https://wordpress.org/support/topic/filter-out-custom-post-types-1
https://wordpress.org/support/topic/cancel-article-submission-to-instant-article-on-post-creation
https://wordpress.org/support/topic/how-i-can-filter-out-the-publications-to-be-instant-articles/
https://wordpress.org/support/topic/filter-by-category-14/
https://wordpress.org/support/topic/v30-allow-filtering-of-post-types-used-in-the-feed-how/

https://wordpress.org/support/topic/instant-articles-for-custom-post-type/

**Comment by kevinlisota** [comment]
Please make sure that there is the ability to prevent custom post types from being pushed. We use a bunch of different custom post types that have no reason being shared with FB instant articles.

**Comment by markbarnes** [comment]
It's already possible to do this by modifying the query. I'm doing that to limit by feed to a particular custom post type.

````php
    add_action ('pre_get_posts', array ('modify_ia_query', 11, 1);

    /**
    * Modifies the WordPress query when the instant articles feed is being requested
    * 
    * @param WP_Query $query  The WP_Query object. Passed by reference.
    */
    function modify_ia_query ($query) {
        if (defined('INSTANT_ARTICLES_SLUG') && $query->is_main_query() && $query->is_feed(INSTANT_ARTICLES_SLUG)) {
            $query->set ('post_type', 'em_article');
        }
    }
````

**Comment by DJUK16** [comment]
@markbarnes would that work for example i only want the NEWS category to become an instant articles and other category to just remain normal.

also if so where would i edit to add this code :D

**Comment by markbarnes** [comment]
You should be able to do something similar for categories. Just create a new plugin with that code (although the sample code only works for the feed, you should be able to modify it). I don't have time to help you with the specifics though, I'm sorry.

**Comment by DJUK16** [comment]
way above my head but thank you for the time to replay sir have a wonderful night!

**Comment by everton-rosario** [comment]
This was fixed by PR #504

**Comment by demoive** [comment]
To clarify, this issue would be to add UI elements into the Advanced Settings for controlling/filtering which posts are published as Instant Articles.

**Comment by Verticalmag** [comment]
Until the UI is created is there a way to proper way to add custom post types without affecting future updates?

**Comment by DJUK16** [comment]
I've found the best way is a rss filter blocking a select post category
from been a FBIA

**Comment by katsar0v** [comment]
Any news about UI control of IA publishing? It's should have been a core feature from the beginning and not just pushing everything like that ...

**Comment by Verticalmag** [comment]
@DJUK16 this worked and looking forward to a UI method. [](https://wordpress.org/support/topic/instant-articles-for-custom-post-type/#post-8643885 )

**Comment by Verticalmag** [comment]
@DJUK16 This worked for me... I'm looking forward to the UI in the future.
https://wordpress.org/support/topic/instant-articles-for-custom-post-type/#post-8643885

**Comment by volokolamskspb** [comment]
Hi, I fixed the plugin. Now there's a checkbox which filters unwanted posts from RSS Feed.
I know it's a bit ugly solution: I added a new table with ID of posts which will be displayed in the feed.
Just install updated the plugin: https://github.com/volokolamskspb/FB_Instant_Articles_wp/
Thanks
