### ISSUE TITLE
How add custom content types to my feed?

### ISSUE THREAD

**Issue by bryan-rojas-liquor** [Automattic/fb-instant-articles#188]
The FB Instant Articles supports only Post type and I'm wondering how to add other type of contents to my feed. Where may I locate the query select to add the content types that I need?

https://github.com/Automattic/facebook-instant-articles-wp/blob/master/facebook-instant-articles.php#L161

Thank you.

**Comment by everton-rosario** [comment]
@bryan-rojas-liquor Thanks for using Instant Articles.
In this case, there is a case about the filtering: https://github.com/Automattic/facebook-instant-articles-wp/issues/186
