### ISSUE TITLE
Option to batch update the modDate of all the feed articles?

### ISSUE THREAD

**Issue by gabu69** [Automattic/fb-instant-articles#200]
Is there any way to update the modDate of all the feed articles?

Let's say I just updated my **Audience Network Placement ID or my Tracking Script** how can I batch update all the articles scraped by Facebook if im using the RSS Feed option?

**Comment by everton-rosario** [comment]
@gabu69 Thanks for sharing this other issue.

The WordPress plugin still doesn't work well with Bulk/batch operations. We will have this soon.

Until there you can use API integration, that works better than RSS and provides you more control, so you could update all your articles, by calling the API for updating the modify date of the articles you need to.
