### ISSUE TITLE
How Support Custom Shortcodes?

### ISSUE THREAD

**Issue by bryan-rojas-liquor** [Automattic/fb-instant-articles#210]
Hi! I have a custom shortcode for my images in my Content so I'd like to know if I could do something to print the markup for images in my Feed using my shorcode o if there is another way to achieve that.

BTW: The FB Instant Articles plugin ignores my shortcode output.

Greetings.

**Comment by alexdelgado** [comment]
I had a similar issue and this is what I came up with the following: 

<code>
if ( defined( 'INSTANT_ARTICLES_SLUG' ) && is_feed( INSTANT_ARTICLES_SLUG ) ) {

	$output = '<div class="gallery">'.

		$output .= '<figure class="op-slideshow">';

		foreach ( $attachments as $id => $attachment ) {

			$attr = ( trim( $attachment->post_excerpt ) ) ? array( 'aria-describedby' => "$selector-$id" ) : '';
			$image_output = wp_get_attachment_link( $id, $size, false, false, false, $attr );

			$output .= '<figure>';

				$output .= "$image_output";

				if ( $captiontag && trim($attachment->post_excerpt) ) {
					$output .= '<figcaption>'. wptexturize($attachment->post_excerpt) . '</figcaption>';
				}

			$output .= "</figure>";

		}

		$output .= '</figure>';

	$output .= '</div>';
} else {
    // do normal markup
}
</code>
