### ISSUE TITLE
Problem with img src url

### ISSUE THREAD

**Issue by ozc** [Automattic/fb-instant-articles#215]
Plugin encodes image source url.

It should be like:
img src="https://www.example.com/wp-content/uploads/2016/04/Ekran-Alıntısı-4.jpg "/>

It is encoded like this:
img src="https://www.example.com/wp-content/uploads/2016/04/Ekran-Al&#x131;nt&#x131;s&#x131;-4.jpg"/>

So the server gives a 400 or 404 error.

**Comment by stuartshields** [comment]
@ozc What language is that? I think it's an issue with the plugin using `utf-8`.

**Comment by ozc** [comment]
Turkish. No problem with the output of the UTF-8 text. File can be accessed without an error, so noproblem with server. The problem is in "Transformed Markup" part.

In post page, output of the url is correct, in error message, where it says "It wasn't possible to submit your article. The server responded with the following messages:"


Even in Facebook Instant Articles list it gives an error, but the error text of the url is shown correctly.
This is for another post:
"General Errors: Could Not Download Image: Your image from URL https://www.example.com/wp-content/uploads/2015/06/inşaat-sektörü.jpg could not be downloaded with an error code 400. Please check to make sure image at https://www.example.com/wp-content/uploads/2015/06/inşaat-sektörü.jpg is active and loads correctly at that URL."
