### ISSUE TITLE
NextGen Gallery shortcodes doesn't work in Instant Articles

### ISSUE THREAD

**Issue by kellemar** [Automattic/fb-instant-articles#222]
When Facebook pulls an article with a gallery, it only shows the shortcode, "[imagebrowser id=1531]", where 1531 is the id of the NextGen gallery.

How do I get Facebook to parse this gallery article properly?

**Comment by everton-rosario** [comment]
@kellemar The only way is to create a custom Rule and add it to your rules.json.

We are implementing the most common plugins rules so you have it converted.

**Comment by DJUK16** [comment]
has this happened yet????

**Comment by zakkdlarte** [comment]
Hi there :)
This is still an issue as Instant Articles still show the [ngg] shortcode instead of the gallery. Any update?
