### ISSUE TITLE
Not posting to FB on quick edit

### ISSUE THREAD

**Issue by nextpulse** [Automattic/fb-instant-articles#229]
Not sure if this is intentional.
On a 'quick edit' - it fails the following in the submit_article():

```
    if ( count($article->getChildren()) === 0 || ! $article->getHeader() || ! $article->getHeader()->getTitle() ) {
        return;
    }
```

The 'quick edit' is useful for those submitting 100s of articles (after being approved), where editing each article and 'update' is not practical.

Ideas?

**Comment by everton-rosario** [comment]
@nextpulse We are working on the bulk update. @diegoquinteiro Is the one that will work on this soon.

Keep posted.
