### ISSUE TITLE
Plugin integration support: Shortcodes Ultimate

### ISSUE THREAD

**Issue by demoive** [Automattic/fb-instant-articles#235]
Add default support for the markup generated by the [Shortcodes Ultimate](https://wordpress.org/plugins/shortcodes-ultimate/) plugin.

One sample:

**Source Markup** (produced from inline: `[su_youtube url="https://www.youtube.com/watch?v=lWVWfpG_6A8"]`)

``` html
<div class="su-youtube su-responsive-media-yes">
  <iframe width="600" height="400" src="http://www.youtube.com/embed/lWVWfpG_6A8" frameborder="0" allowfullscreen="true"></iframe>
</div>
```

References:
https://wordpress.org/support/topic/content-inside-shortcode-is-omitted?replies=9

**Comment by demoive** [comment]
Tested Rule for the YouTube example in the description:

**Rule**
```html
{
    "class": "SocialEmbedRule",
    "selector" : "div.su-youtube",
    "properties" : {
        "socialembed.url" : {
            "type" : "string",
            "selector" : "iframe",
            "attribute": "src"
        }
    }
}
```

**Comment by donaldG** [comment]
@demoive nice! I suspect there's lots of folks who will benefit from this. We use a custom shortcode to output a YouTube player and/or multiplayer so that it's responsive and we have more control over it.
