### ISSUE TITLE
Integration support: WP Shortcodes and oEmbeds

### ISSUE THREAD

**Issue by demoive** [Automattic/fb-instant-articles#236]
Add default support for the markup generated by [WordPress Shortcodes](https://en.support.wordpress.com/category/shortcodes/) and [WordPress oEmbeds](https://codex.wordpress.org/Embeds).

References:
https://wordpress.org/support/topic/content-inside-shortcode-is-omitted (`[recipe]`)
https://wordpress.org/support/topic/correct-transformer-rule-for-caption-shortcode (`[caption]`)
https://wordpress.org/support/topic/twitter-logo-displayed-instead-of-site-logo  (`[twitter]`)

https://github.com/Automattic/facebook-instant-articles-wp/issues/158
https://github.com/Automattic/facebook-instant-articles-wp/issues/225
https://github.com/Automattic/facebook-instant-articles-wp/issues/142

**Comment by bactisme** [comment]
####  Embeds

**How to do**
Either past a blog URL, or use the shortcode `[embed url=""]` (not sure)

**Code printed in content**

```
<blockquote data-secret="zfmpJWV4pR" class="wp-embedded-content"><p><a href="http://www.numerama.com/tech/151474-voitures-autonomes-tout-savoir-sur-lautomobile-du-futur.html" >Voiture autonome&#160;&#160;: Où en sont les constructeurs&#160;&#160;? (Google, Tesla, Volvo, Renault&#8230;)</a></p></blockquote>
<p><iframe class="wp-embedded-content" sandbox="allow-scripts" security="restricted" style="display:none;" src="http://www.numerama.com/tech/151474-voitures-autonomes-tout-savoir-sur-lautomobile-du-futur.html/embed/#?secret=zfmpJWV4pR" data-secret="zfmpJWV4pR" width="100%" height="282" title="Inclure un article WordPress" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></p>
```

**Code present in instant article**

```
<blockquote><a href="http://www.numerama.com/tech/151474-voitures-autonomes-tout-savoir-sur-lautomobile-du-futur.html#utm_medium=distibuted&amp;utm_source=fbinstant&amp;utm_campaign=168734">Voiture autonome  : Où en sont les constructeurs  ? (Google, Tesla, Volvo, Renault…)</a>
</blockquote><figure class="op-social"><iframe src="http://www.numerama.com/tech/151474-voitures-autonomes-tout-savoir-sur-lautomobile-du-futur.html/embed/#?secret=zfmpJWV4pR"></iframe></figure>
```

**Problem**

`<figure class="op-social">` is not adequate, but it seems to work if it's op-interactive, but if it's loaded, the blockquote is useless.

**Comment by demoive** [comment]
Tracking a suggested solution in WP Forums for the `[recipe]` shortcode:

```html
{
  "class": "PassThroughRule",
  "selector": ".hrecipe,.jetpack-recipe-content"
}
```
