### ISSUE TITLE
Extracting the Image caption under the image

### ISSUE THREAD

**Issue by warrenlee** [Automattic/fb-instant-articles#266]
Is there a way to get the image caption that's under the image itself (or link in this case)?

```
<p>
    <a href="http://link-to-image.com">
        <img class="alignnone size-full wp-image-18528" src="http://self-hosted-image">
    </a>
The image caption here
</p>
```

**Comment by donaldG** [comment]
@warrenlee if you're able to change your markup at all it gets a bit easier. Using HTML5 elements makes it super easy. I've had little success using any of the filters in this plugin but writing [Custom Transformer Rules](https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules) and/or changing my markup is working swimmingly. 

So, for markup, you could try:

```
<figure>
    <a href="#link">
        <img class="blah blah" src="img.jpg">
    </a> 
    <figcaption>The Image caption here</figcaption>
</figure>
```

And that would definitely output it correctly.

Alternatively, if you want to change the markup minimally and say add a "p" tag around your caption with a class of "caption" then you could write a Custom Transformer Rule (base CaptionRule of this plugin: https://github.com/Automattic/facebook-instant-articles-wp/blob/master/rules-configuration.json#L231), something like:
```
{
    "class": "CaptionRule",
    "selector" : "p.caption"
},
```

**Comment by warrenlee** [comment]
Hi @donaldG thanks for your reply and sorry for the late response.
I'm trying to avoid altering any markup since the blogger has gone for the easier approach [insert image, new line, caption, new line, insert image] etc, rather than upload image, type caption, insert image.

Will try and look for other work arounds.
