### ISSUE TITLE
Ability to flush feed

### ISSUE THREAD

**Issue by drrobotnik** [Automattic/fb-instant-articles#270]
We had an issue where the another plugin/service was applying data to the_content, that was not being correctly validated preventing us from being approved for FB-IA. I was able to remove the action easily, but flushing the cached feed was impossible. It looks like currently it only updates when the post is updated.

I propose adding some ability to flush the feed via an interface within the dashboard.

**Comment by rinatkhaziev** [comment]
I agree it's pretty annoying, I have following helper for that: 
```php
/**
 * Facebook Instant Articles uses transients to store content for a week, unless updated
 * since we're in dev we need to flush it often
 *
 * @return [type] [description]
 */
function flush_transients() {
	$latest = new \WP_Query( [
		'posts_per_page' => self::TOTAL_POSTS,
		'fields' => 'ids',
		'orderby' => 'modified',
		'no_found_rows' => true,
		] );

	foreach ( $latest->posts as $id )
		delete_transient( 'instantarticles_content_' . $id );
}
```

**Comment by everton-rosario** [comment]
@rinatkhaziev can you create a PR with that feature?
