### ISSUE TITLE
Option for displaying featured image as header image

### ISSUE THREAD

**Issue by diplatis** [Automattic/fb-instant-articles#274]
Hi,

it would very handy if there was an option for displaying or not the featured image in wordpress as header image in instant article. Many wordpress blogs use the main article image as featured and so it gets displayed twice in the instant article.

**Comment by gandrewnorman** [comment]
This is also a request I would much like to see as I am using listicles and this is a very similar issue I am having.

**Comment by jeremyclarke** [comment]
This seems like an inherent drawback to iA. Like other services, it assumes you have a metadata-driven featured image in the stye of the Twenty Fourteen theme, and which is not also present in the post itself. This is a fairly common pattern with new themes, but IMHO a terrible assumption to make. We want our posts to be whole and images are part of the story, I don't want the image/caption for the main image to live only outside the post content, where they would by default be missing from RSS, Instapaper and other services that use RSS or raw content. 

I'm not sure if FB will allow you to have posts without a header image, so you're probably better off just ignoring the problem. I read in the FB guidelines that it's against the rules to duplicate an image, but if they allowed you to do so then just be glad you're getting away with it.
