### ISSUE TITLE
Check box to disable Instant Articles on a Post

### ISSUE THREAD

**Issue by noumaan** [Automattic/fb-instant-articles#275]
It would be nice to have options that allow site owners to choose which articles they want to appear in their Instant Articles feed. A checkbox in the 'Facebook Instant Articles' metabox below the post editor would be very useful. 

Another way is to allow site owners to choose a tag or category for articles they want to automatically add into Instant Articles feed.

**Comment by katsar0v** [comment]
Yes, I would really love to have that, and guess it is not that complicated to build

**Comment by katsar0v** [comment]
Any update on this feature? I guess it is a must for such a plugin

**Comment by cuckoofordeals** [comment]
Yes I would love this as well!

**Comment by donaldG** [comment]
@noumaan @katsar0v @cuckoofordeals I was able to achieve this by creating a category specifically for the Instant Articles. Figuring out that feed URL was a bit of a pain. What I figured out was after creating the Category my feed was this:
http://www.site.com/category/fb-instant-articles-your-custom-cat-name/feed/instant-articles

The documentation isn't super clear on that. Just after trial & error I discovered it. This is also without setting a custom INSTANT_ARTICLES_SLUG. I think all that would do is change 'instant-articles' above to 'your-custom-instant-articles-slug' but everything else would be the same.

**Comment by stuartshields** [comment]
@donaldG You don't need /feed/ in the URL (well I haven't come across any instances of needing this).

**Comment by donaldG** [comment]
Woah, you're right. I couldn't get it working any other way but you're
totally right. In addition, /feed/ does work, for whatever that's worth.

**Comment by katsar0v** [comment]
Somehow posts still get published, though they are basically not in the feed:

https://github.com/Automattic/facebook-instant-articles-wp/issues/460

**Comment by katsar0v** [comment]
Still no updates, but I see this as a major issue

**Comment by volokolamskspb** [comment]
Hi, I fixed the plugin. Now there's a checkbox which filters unwanted posts from RSS Feed.
I know it's a bit ugly solution: I added a new table with ID of posts which will be displayed in the feed.
Just install updated the plugin: https://github.com/volokolamskspb/FB_Instant_Articles_wp/
Thanks

**Comment by daffsandcomp** [comment]
can someone please explain to me in the most simple way possible if there is a way of turning of instant articles for certain posts?
