### ISSUE TITLE
Google Analytics by Yoast integration after post update

### ISSUE THREAD

**Issue by diplatis** [Automattic/fb-instant-articles#283]
When I update a post the Analytics Code in the Instant Article op-tracker is wrong:

`````` html
<figure class="op-tracker"><iframe><!-- This site uses the Google Analytics by MonsterInsights plugin version 5.5 - https://www.monsterinsights.com/ --><!-- @Webmaster, normally you will find the Google Analytics tracking code here, but you are in the disabled user groups. To change this, navigate to Analytics -> Settings (Ignore usergroups) --><!-- / Google Analytics by MonsterInsights --></iframe></figure>```
``````

**Comment by stuartshields** [comment]
@diplatis Google Analytics by Yoast is now Google Analytics by Monster Insights. The issue you're having is easily resolved by going into the settings for Google Analytics by Monster Insights and removing Admin from the Ignore user groups as stated in your code snippet.

`<!-- This site uses the Google Analytics by MonsterInsights plugin version 5.5 - https://www.monsterinsights.com/ --><!-- @Webmaster, normally you will find the Google Analytics tracking code here, but you are in the disabled user groups. To change this, navigate to Analytics -> Settings (Ignore usergroups) -->`

**Comment by diplatis** [comment]
That's not a resolution, it's a workaround as I don't want administrators and editors to be tracked.

**Comment by stuartshields** [comment]
@diplatis Well you need to talk to Monster Insights for a solution.
