### ISSUE TITLE
Non-static method DOMDocument::loadHTML() should not be called statically

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/fb-instant-articles#306]
The FBIA plugin is generating this warning:

```
PHP Deprecated:  Non-static method DOMDocument::loadHTML() should not be called statically, 
assuming $this from incompatible context in
/srv/www/wp-content/themes/vip/plugins/facebook-instant-articles-2.11/class-instant-articles-post.php
on line 617
```

```
Stack trace:
1. {main}() /srv/www/wp/wp-admin/post.php:0
2. edit_post() /srv/www/wp/wp-admin/post.php:193
3. wp_update_post() /srv/www/wp/wp-admin/includes/post.php:369
4. wp_insert_post() /srv/www/wp/wp-includes/post.php:3606
5. do_action() /srv/www/wp/wp-includes/post.php:3533
6. call_user_func_array:{/srv/www/wp/wp-includes/plugin.php:524}() /srv/www/wp/wp-includes/plugin.php:524
7. Instant_Articles_Publisher::submit_article() /srv/www/wp/wp-includes/plugin.php:524
8. Instant_Articles_Post->to_instant_article() /srv/www/wp-content/themes/vip/plugins/facebook-instant-articles-2.11/class-instant-articles-publisher.php:48
```

**Comment by stuartshields** [comment]
@paulschreiber I've come across this warning several times and it's been straight after I've attempted to apply an invalid Rule. Can you confirm the steps before this error happens? Can you also supply the current rules you're using so I can help.

**Comment by paulschreiber** [comment]
I installed the plugin and entered the app ID and secret. I didn't configure or attempt to use anything specific.

**Comment by rinatkhaziev** [comment]
@stuartshields I don't think this has anything to do with rules. Per docs (http://php.net/manual/en/domdocument.loadhtml.php) :

> The static invocation may be used when no DOMDocument properties need to be set prior to loading.
> This method may be called statically, but will issue an E_STRICT error.

**Comment by stuartshields** [comment]
@rinatkhaziev I've only ever come across it when a Rule is incorrectly set. But it's good to know it's not just related to it.

**Comment by paulschreiber** [comment]
Looks fixed in https://github.com/Automattic/facebook-instant-articles-wp/pull/308

**Comment by GaryJones** [comment]
Closing as fixed.
