### ISSUE TITLE
Arabic articles appear as a question marks (??????)

### ISSUE THREAD

**Issue by mazilia** [Automattic/fb-instant-articles#384]
# Steps required to reproduce the problem
1. 
2. 
3. 
# Expected Result
- Showing Arabic letters normally
# Actual Result
- Articles written in Arabic, appears in this form : ????? ????? ???????? ???? ?????? ???? ????

---

*\* Version Info **
- Plugin version: 3.0.1
- WordPress version: 4.5.3
- PHP version: PHP 5.4.45

**Comment by mazilia** [comment]
![img_2025](https://cloud.githubusercontent.com/assets/20703586/17215192/fba3f3c0-54d3-11e6-967c-ba06672d8c96.PNG)

**Comment by mazilia** [comment]
![img_2025](https://cloud.githubusercontent.com/assets/20703586/17220262/6cc3705a-54e6-11e6-8de5-851647ce3636.jpg)

**Comment by everton-rosario** [comment]
@mazilia thanks for your report. we are still working on this i18n issues.
If you come up with some solution, please share with us.

**Comment by sakatam** [comment]
Hi @mazilia, I have been trying to reproduce this but with no luck. Could you provide detailed info about the database as well? Please run the following commands on mysql cli, and put the result here? 

```sql
SHOW VARIABLES LIKE "version%";
```

```sql
SHOW CREATE TABLE wp_posts;
```

Thank you in advance for your help!

**Comment by mazilia** [comment]
SHOW VARIABLES LIKE "version%";
-----------------------------------------
version : 5.6.30
version_comment :  MySQL Community Server (GPL)
version_compile_machine :  x86_64
version_compile_os : Linux
-----------------------------------------
SHOW CREATE TABLE wp_posts;
-----------------------------------------
wp_posts :
CREATE TABLE `wp_posts` (
 `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 `post_author` bigint(20) unsigned NOT NULL DEFAULT '0',
 `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `post_content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
 `post_title` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `post_excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `post_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'publish',
 `comment_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
 `ping_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
 `post_password` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `post_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `to_ping` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `pinged` text COLLATE utf8mb4_unicode_ci NOT NULL,
 `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
 `post_content_filtered` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
 `post_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
 `guid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `menu_order` int(11) NOT NULL DEFAULT '0',
 `post_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'post',
 `post_mime_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
 `comment_count` bigint(20) NOT NULL DEFAULT '0',
 PRIMARY KEY (`ID`),
 KEY `post_name` (`post_name`(191)),
 KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),
 KEY `post_parent` (`post_parent`),
 KEY `post_author` (`post_author`)
) ENGINE=InnoDB AUTO_INCREMENT=13050 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

**Comment by mazilia** [comment]
I think the problem is in this line =>

-------------------
class-instant-articles-post.php
line : 679
-----------------
// DOMDocument isn’t handling encodings too well, so let’s help it a little.
		if ( function_exists( 'mb_convert_encoding' ) ) {
			$content = mb_convert_encoding( $content, 'HTML-ENTITIES', get_option( 'blog_charset' ) );
		} else {
			**$content = htmlspecialchars_decode( utf8_decode( htmlentities( $content, ENT_COMPAT, 'utf-8', false ) ) );**
		}

**Comment by sakatam** [comment]
@mazilia Thank you so much for your prompt reply, and pointing out the problematic part! I will take a deeper look into this line.
