### ISSUE TITLE
Option hide "author name"

### ISSUE THREAD

**Issue by mazilia** [Automattic/fb-instant-articles#439]
# Steps required to reproduce the problem
1. 
2. 
3. 
# Expected Result
- Option for change direction to RTL in plugin settings
- Option for hide the author name in plugin settings
# Actual Result
- I can't change the direction
- I can't hide the author name

---

*\* Version Info **
- Plugin version: 3.1.2
- WordPress version: 4.6
- PHP version: 5.4.45

---

the programming solution to change the direction to "RTL" : 
is add this line =>
`$html->setAttribute('dir','rtl');`
in line 329 of _/wp-content/plugins/fb-instant-articles/vendor/facebook/facebook-instant-articles-sdk-php/src/Facebook/InstantArticles/Elements/InstantArticle.php_ 
after 
`$html = $document->createElement('html');`

**Comment by demoive** [comment]
@mazilia this issue deals with 2 individual requests. Treating them separately:

1. **RTL:** Good suggestion! Let's follow this in the existing #317
2. **Hide Author:** Can you provide a use case/reason you'd want to hide the author name from the article? This will help factor the priority of this feature request.

**Comment by demoive** [comment]
Since the RTL issue is a duplicate of #317, I'm changing the title of this issue to reflect the 2nd request.

**Comment by trewknowledge** [comment]
I have a situation where I don't want to display the author since our site does not show this information on our website.

Do you know if this is currently possible to remove the `<addresss>` tag where the author is displayed?

**Comment by trewknowledge** [comment]
Filtering into `instant_articles_authors` works for me. Thanks!

**Comment by selvambe23** [comment]
HI Trewknowledge,

how to use this instant_articles_authors in function.php file for hide author name in facebook instant article.

thanks in advance

**Comment by trewknowledge** [comment]
@selvambe23 something like this: 

```
function tk_instant_articles_authors( $authors, $post_id) {
	$authors = array();
    return $authors;
}
add_filter('instant_articles_authors', 'tk_instant_articles_authors', 10, 2);
```

**Comment by selvambe23** [comment]
Thanks @trewknowledge.

**Comment by jas88934** [comment]
@trewknowledge @selvambe23 Where do you insert that code? I'd like to get rid of the "author" for good since our site doesn't use authors, but I'm relatively new to all of this and am not sure where to insert the code you wrote above. Thanks in advance for any help you can give to a noob like me!

**Comment by selvambe23** [comment]
Hello @jas88934 ,

I was out of station for last few days. place the above code in your theme functions.php end of the file. it will work.

**Comment by jas88934** [comment]
@selvambe23 Man, thank you!! It worked! I really appreciate the help.

**Comment by nders84** [comment]
hi all @trewknowledge @selvambe23 
I'd like to replace the author with a custom field 'author'. Have been fiddling forever but can't seem to get it to work. Can anyone help? Thanks!

**Comment by eduardopintor** [comment]
Hi use this code
