### ISSUE TITLE
Translation doesn't working properly

### ISSUE THREAD

**Issue by brunohulk** [Automattic/fb-instant-articles#44]
Hi guys, I am trying to help to improve the plugin, so I've created the pt_BR translation including the po and mo files, but, it wasn't working for me.
Then I've made a few changes in the way that plugin load the mo files, so, I was able to load the plugin translation.
You can see this change on this pull-request below, if there is any problem with the pull request, let me know.

You can check this on https://github.com/brunohulk/facebook-instant-articles-wp/pull/1

**Comment by philipjohn** [comment]
Thanks for taking a look at this @brunohulk !

Looks like something has gone wrong with the PR though: https://github.com/brunohulk/facebook-instant-articles-wp/pull/1/commits

You probably need to update your fork, make new commits to it and then visit https://github.com/Automattic/facebook-instant-articles-wp to see the prompt to create a Pull Request here.

**Comment by brunohulk** [comment]
@philipjohn My fault, this is the right pull request https://github.com/Automattic/facebook-instant-articles-wp/pull/45

**Comment by philipjohn** [comment]
Great, thanks.

I'm pretty sure the change to `instant_articles_load_textdomain()` is uneccessary - can you talk me through how you tested your translation, what you expected, and what you actually saw please?

Also, looks like the PR introduces a bunch of unnecessary spacing changes to `tests/test-class-instant-articles-post.php` - could we get those reverted please?

**Comment by bjornjohansen** [comment]
A change to `instant_articles_load_textdomain()` is actually neccessary, but the way it’s done in #45 isn’t best practice. I’ve included proper translation loading in #46 

My apologies to @brunohulk, as the provided POT file wasn’t updated when the plugin header was updated a while back. #46 includes an updated POT file.

I suggest we reject #45, merges #46 and asks @brunohulk to kindly provide new files for pt_BR based on the updated POT.

**Comment by brunohulk** [comment]
Ok @bjornjohansen tks, I agree with you I can do that as soon as the #46 be merged, the 45 isn`t the best approach.
Have you test your approach?

**Comment by brunohulk** [comment]
About the removing spaces is a small refactor that I did to improve the code quality, but is in the wrong merge request, the right patch for this is in https://github.com/Automattic/facebook-instant-articles-wp/pull/42, can you see that? Is just a sugestion @philipjohn

**Comment by philipjohn** [comment]
@brunohulk We've left this issue behind a bit because we've released v2.11

Do you want to update this PR to merge against the latest version and then we can get it merged :)

Thanks so much for putting the effort in!
