### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by Nmidia** [Automattic/fb-instant-articles#445]
Hi,

Is there a way of getting around the problem of poor image quality when using anything but full sized images?  If I insert a thumbnail image in WP, it is very low quality in FBIA.  If I use "Full" sized images the quality is great.  However, I don't want to have full sized images in my online post as they look messy and take up too much page space.

Thanks

**Comment by toby1kenobi** [comment]
Did you get anywhere with this, I have the same problem?

**Comment by Nmidia** [comment]
Unfortunately, no.  I ended up using the full size images.

**Comment by toby1kenobi** [comment]
Ok, thanks for letting me know
