### ISSUE TITLE
Commenting / Like at the Article Level Not Functional

### ISSUE THREAD

**Issue by krispy1298** [Automattic/fb-instant-articles#489]
# Expected Result
- Like and Comments appear for the whole article.
# Actual Result
- Cannot like or comment on article.

---

functions.php includes:

```
function paInstantArticlesTransformedFilter($ia) {
    $ia->addMetaProperty('fb:likes_and_comments', 'enable');
    return $ia;
}
add_filter( 'instant_articles_transformed_element', 'paInstantArticlesTransformedFilter' );
```

Visible in Transformed Markup:

```
<meta property="fb:likes_and_comments" content="enable"/>
```

**Comment by Infini7y** [comment]
Having the same problem.

**Comment by demoive** [comment]
Hi @krispy1298. As you may know, this setting is controlled in the Configuration > Tools > Feedback Settings section of your Facebook Page:

![feedback-settings](https://cloud.githubusercontent.com/assets/472288/19196844/0b8f0d52-8caf-11e6-8c87-2336d7ddad72.png)

This plugin doesn't set the`<meta property="fb:likes_and_comments" content="disable">`option therefore the settings is purely controlled by the setting in your Facebook Page configuration.

If the Like and Comment UI isn't appearing, there must some other underlying reason; setting it [explicitly within the markup](https://developers.facebook.com/docs/instant-articles/reference/feedback) as you suggested shouldn't be necessary.

I am double checking the possible reason and will reply soon.

**Comment by apollosk** [comment]
I have the same problem, even with the appropriate option box checked in Configuration > Tools > Feedback Settings section of our Facebook Page  and <meta property="fb:likes_and_comments" content="disable"> added manually.

**Comment by demoive** [comment]
@krispy1298 @apollosk can I where are you observing this behaviour? Is it from the Pages app or from within the normal Facebook app after clicking the link on a post?

**Comment by apollosk** [comment]
@demoive Both Pages app and normal Facebook app.

**Comment by demoive** [comment]
Thanks @apollosk. I'd like to look into the case where this reproduces in the Facebook app. Are you able to direct me to a Facebook post where you've observed this issue so that I can try to reproduce and investigate further.

**Comment by apollosk** [comment]
@demoive You may take a look at whatever post on https://www.facebook.com/queermk/

**Comment by demoive** [comment]
@apollosk I tested the first ~10 posts on the Queer.mk page and all the Instant Articles are rendered with Like and Comment UI (in the Facebook app). If you know of a particular case where it's not rendered, can you direct me to it?

**Comment by demoive** [comment]
@apollosk I will try to double check for you. Two quick favours:

1. Make sure you're on the latest version of the app
2. Provide a screenshot of it not rendering, preferably for this same article [here](https://www.facebook.com/queermk/posts/1398422673505260):

![img_4101](https://cloud.githubusercontent.com/assets/472288/19510907/f6ad5dee-95dc-11e6-839f-aced31acdd9d.PNG)

**Comment by apollosk** [comment]
@demoive I'm using the latest version of the Facebook app. [Click here for a screenshot](https://drive.google.com/open?id=0B7-LV0sT2jK0TkZYQjAtZmtKdHc).

**Comment by kampit** [comment]
Having same problem.

Visible in Transformed Markup:

  ```
<meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
<meta property="op:generator:version" content="1.5.0"/>
<meta property="op:generator:application" content="facebook-instant-articles-wp"/>
<meta property="op:generator:application:version" content="3.2.2"/>
<meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
<meta property="op:generator:transformer:version" content="1.5.0"/>
<meta property="fb:likes_and_comments" content="enable"/>
<meta property="op:markup_version" content="v1.0"/>
<meta property="fb:use_automatic_ad_placement" content="true"/>
```

**Comment by VivekManglani** [comment]
I'm having the same problem...

**Comment by krispy1298** [comment]
Do the like buttons not come up for the managers of the page?

**Comment by VivekManglani** [comment]
So from my observation, it seems like it's the related articles that have issues with comments. There is 1 article we have that we've published on our page. That article supports likes & comments. However, when you scroll down and go to a related article, the comment feature doesn't work.

![iascreenshot](https://cloud.githubusercontent.com/assets/6572849/25006635/4ba158d0-2090-11e7-8f5b-78f9a1571369.jpeg)

Moreover, we are also seeing some articles (that are not published on wall) have the big share button instead of the Like Comment Share buttons. Like [this](https://drive.google.com/file/d/0B7-LV0sT2jK0TkZYQjAtZmtKdHc/view) by @apollosk 

The Page in Question is: https://www.facebook.com/JetLi/
