### ISSUE TITLE
Update compat name from Yoast to MonsterInsights

### ISSUE THREAD

**Issue by demoive** [Automattic/fb-instant-articles#496]
# Steps required to reproduce the problem
1. Install this compat plugin: https://wordpress.org/plugins/google-analytics-for-wordpress/
2. Observe the name shown in **Advanced Settings** > **Analytics** > **3rd Party Integrations**
# Expected Result
- Google Analytics by MonsterInsights
# Actual Result
- Google Analytics by Yoast

---

We can either change the name explicitly or update the logic to grab the name from within the plugin.

**Comment by everton-rosario** [comment]
@demoive Can you please review and double test this?

**Comment by demoive** [comment]
This one fell through. Reviewed and approved the PR. Thanks @everton-rosario.
