### ISSUE TITLE
Notify users of useless/invalid transformations

### ISSUE THREAD

**Issue by jerclarke** [Automattic/fb-instant-articles#512]
The problem is that there is no validator for transformations, and the transformations documentation is horrifically lacking in complex examples and specifically absent is any discussion of the MANY completely impossible transformations that seem like they should work. 

What would be extremely useful is a system that identifies impossible transformations and shows warnings in the Advanced Settings section that they won't work. 

For example (ignore format, I set them up with PHP arrays, not the point):

```
'class' => 'H2Rule',
'selector' => 'blockquote h3'
```

This rule seems logical, but will always fail because you cannot have H2Rule in anything except the main raw container. Adding this rule does absolutely nothing and could never do anything. It's extremely similar to transformations that DO work though, so I ended up doing hours of debugging trying to figure out why it wasn't registering, when an algorithm could have just told me "why are you trying this transformation, it's impossible". 

FWIW part of the problem is Facebook's dramatically mediocre documentation: https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules#rule-context

It tries but fails to clearly explain "context" as it applies to transformations, and gives no examples at all of what a contextually-invalid transformation would look like (e.g. the one above), nor how to work around them. There are literally infinite contextually-invalid transformations that will drive people crazy trying to understand, and neither the docs nor this plugin give us any help at all :(

I realize this ticket may be a fantasy but I believe it's the only way that normal users who don't have weeks to devote to iA would be able to set up the transformations that are possible without wasting hours on transformations that will never work.

**Comment by diegoquinteiro** [comment]
Thanks a lot for your feedback. I apologize that our docs weren't clear enough on explaining the works of the context-aware rules, and we'll take your ideas in consideration to improve them.

The tool to automatically check for invalid contexts a little trickier though, as, for example, your rule would actually be useful if you also had a "PassThroughRule" for blockquote.

**Comment by jeremyclarke** [comment]
> The tool to automatically check for invalid contexts a little trickier though, as, for example, your rule would actually be useful if you also had a "PassThroughRule" for blockquote.

Yeah sure, because PassThroughRule works in all contexts, so this possible validator wouldn't red-flag any PassThroughRule rules. 

BUT H2Rule only works in the root context, so ANY selector that had more than one level is an immediate red flag and you could say "blockquote H3 is an invalid selector for H2Rule, H2Rule only works in InstantArticle (root) context [link to help doc explaining root context]"

This would have saved me wasting my time on a totally impossible rule definition AND taught me how to proceed with my other attempts (in my case a long list of similar non-root-context rules that also won't work).
