### ISSUE TITLE
Unpublish a live FBIA

### ISSUE THREAD

**Issue by cmjaimet** [Automattic/fb-instant-articles#517]
# Steps required to reproduce the problem

1. Set some parameter on a post after it has already been sent to Facebook as an Instant Article on a previous save.
2. Save the post
3. The parameter set will determine if a post should be removed from Instant Artcies on Facebook

# Expected Result

* A post with the "off" parameter will remove or unpublish the existing Instant Article related to this post

# Actual Result

* Facebook Instant Articles remain active and published no matter what is changed on the Wordpress post once they have been published to Facebook.

---

** Version Info **

Plugin version: 1.3
WordPress version: 4.6.1
PHP version: 5.x

**Comment by anthonyeden** [comment]
Hello,

Just wanted to check in and see if anyone is working on this issue?

Thanks,
Anthony.

**Comment by anthonyeden** [comment]
Hello,

I just wanted to check in and see if anyone had thoughts re: #1031. The sticking point seems to be these app permissions. Is anyone aware of a best-practice way to overcome the issues detailed in this PR?

Thanks,
Anthony.

**Comment by anthonyeden** [comment]
@cmjaimet @diegoquinteiro @everton-rosario I'm really sorry to tag a few people here, but this PR & Issue has had no attention. Is this project abandoned?
