### ISSUE TITLE
1 Warning & 1 Error in PHP 7 

### ISSUE THREAD

**Issue by gabu69** [Automattic/fb-instant-articles#528]
Recently I installed <a href="https://wordpress.org/plugins/php-compatibility-checker/" target="_blank">PHP Compatibility Checker plugin</a> to check if all my plugins where compatible with PHP 7. 

Your plug in displays these Warnings/Errors:

`FILE: /var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterXML.php
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 | WARNING | File has mixed line endings; this may cause incorrect results
--------------------------------------------------------------------------------------------------------------------------------------------------------------------

FILE: /var/www/site.com/public_html/wp-content/plugins/fb-instant-articles/vendor/apache/log4php/src/examples/php/appender_socket_server.php
---------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------------------------
 57 | ERROR | Function split() is deprecated since PHP 5.3 and removed since PHP 7.0; use preg_split instead
---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by cgidds** [comment]
Has there been any additional traction on this enhancement/feature request? We're trying to migrate to PHP7.1 and would like this (at least the error) resolved.

**Comment by pestevez** [comment]
This is not an issue that has been prioritized by our team yet.

In any case, by looking at the path to the file with the error, it looks like it is coming from the examples folder of one of our dependencies, which means that this is NOT code that we are executing. Also, we have been using the plugin on sites running PHP 7+ for a while and this has never been a problem.

I am not familiar with the PHP Compatibility Checker plugin, but per their messages:

> Attention: Not all errors are show-stoppers. Test this site on PHP 7 to see if it just works!

and 

> This tool cannot detect unused code paths that might be used for backwards compatibility, potentially showing false positives.

The solution to this issue might be as simple as deleting the `vendor/apache/log4php/src/examples` in the plugin release script. CC: @diegoquinteiro

**Comment by GaryJones** [comment]
Agreed that this is not a valid concern.
