### ISSUE TITLE
Article content truncated with [...] by the RSS Post Importer plugin

### ISSUE THREAD

**Issue by demoive** [Automattic/fb-instant-articles#546]
# Steps required to reproduce the problem

1. Install the (non-paid) [RSS Post Importer](https://wordpress.org/plugins/rss-post-importer/) plugin.

# Expected Result

* The final post/page content used for the WP plugin should not be truncated by other plugins.

# Actual Result

* The post/page content is truncated (with a trailing `[...]`).

**Comment by Daconixxx** [comment]
Can anyone help me with RSS , stoped upload before 15 hours,now it say i dont have any instant articles and i need to upload 10 new,but cant because RSS stoped here is ss
![rss1](https://user-images.githubusercontent.com/50676658/59369312-70b76000-8d40-11e9-8a73-0d745b6e88dd.png)

**Comment by Daconixxx** [comment]
Now I got this  ahhahahah It is my lucky day
![lost1](https://user-images.githubusercontent.com/50676658/59370530-ff2ce100-8d42-11e9-9582-cc1757bb7738.png)
