### ISSUE TITLE
Hooks - what hooks are there?

### ISSUE THREAD

**Issue by toby1kenobi** [Automattic/fb-instant-articles#547]
Plugin page (https://en-gb.wordpress.org/plugins/fb-instant-articles/) says, "It's important to note that if you use meta fields to add extra text, images or videos to your Posts, Facebook will expect you to add these to your Instant Articles output too. This plugin includes hooks to help you do that." - are these documented anywhere?

Thanks.

**Comment by diegoquinteiro** [comment]
Hi @toby1kenobi,

They are not properly documented indeed.

You can use the `instant_articles_transformed_element` filter to modify the final InstantArticle instance before it is submitted. 

See our SDK for docs on manipulating this object: https://github.com/facebook/facebook-instant-articles-sdk-php
