### ISSUE TITLE
Currently no gallery plugin supported

### ISSUE THREAD

**Issue by DJUK16** [Automattic/fb-instant-articles#573]
Basically there is NO gallery option that looks good on both FBIA /site view! 

how long will it be until its made more clear how to so stuff needs to be converted to work correctly please don't reply with make a transform rule because i clearly don't know how to do that or i would of.

Can anyone please point me in the right direction of a gallery that will look and work correctly on both site view and FBIA? 

One with a single image thumbnail (click to view gallary) 

**Version Info**

* Plugin version: latest
* WordPress version: latest
* PHP version: latest

**Comment by jeremyclarke** [comment]
This goes into the greater issue of having documentation for the plugin that makes up for the lack of docs from FB and in particular shares how to best solve problems like transformers within the plugin's UI.

**Comment by timjacobi** [comment]
This seems to be a more general instance of #574 which asks for support for foo.gallery
Maybe we can pick one supported gallery plugin.
