### ISSUE TITLE
Where do we learn about Analytics 3rd Party Integration?

### ISSUE THREAD

**Issue by jerclarke** [Automattic/fb-instant-articles#608]
I want to create an integration for the plugin I use. Can't find a guide or docs anywhere. Tried searching here for third party,  3rd party, analytics etc. 

Would be excellent to have this info on the WP.org page to increase likelihood of plugins adding support, and make it easy for those of us who want to create our own. 

Would also be great to have a link to this repo from the WP.org page.

**Comment by koconder** [comment]
I contribute to a number of analytics plugins on Wordpress. Happy to assist with the likes of Chartbeat, Google Analytics and Google Tag Manager support and extending compatibility with other 3rd party apps.

If we have hooks available id be more than happy to look into some common setups. Using widely used WP plugins that handle analytics.

**Comment by everton-rosario** [comment]
Hey @jerclarke, as @robbiet480 did here, is a good one to go:
https://github.com/Automattic/facebook-instant-articles-wp/pull/941
