### ISSUE TITLE
Apester Medias support for Facebook Instant Articles

### ISSUE THREAD

**Issue by oraricha** [Automattic/fb-instant-articles#610]
# Steps required to reproduce the problem

1. Insert embed code of an [Apester](https://wordpress.org/plugins/apester-interactive-content/) media into a post/page in WordPress editor, e.g: 
`<div class="apester-media" data-media-id="589bc9a8756b9aa56ab39728"></div>`
2. Try to update/publish the article
3. look at the Facebook Instant Articles metabox

# Expected Result

* The Apester markup should convert into a valid FB IA markup, e.g:
`<figure class="op-interactive">
        <iframe class="no-margin">
          <script type="text/javascript" src="//static.apester.com/js/sdk/latest/apester-sdk.min.js"></script>
          <div class="apester-media" data-media-id="589bc9a8756b9aa56ab39728"></div>
        </iframe>
      </figure>`

# Actual Result

* The markup is not recognised by any transformer rule by default. Each author/ publisher has to manually insert the Apester transformer rule into the plugins settings.

# Suggested Solution
* I've proposed a [PR #609 ](https://github.com/Automattic/facebook-instant-articles-wp/pull/609) for fixing this issue. It has passed CI already. Please review and approve when possible.

---

**Version Info**

* Plugin version: 3.3.1
* WordPress version: 4.7.2
* PHP version: 7.0.12

**Comment by diegoquinteiro** [comment]
Thank you so much for your contribution! I'll be reviewing it today.

**Comment by GaryJones** [comment]
Fixed in #609.
