### ISSUE TITLE
Ad Placement Configuration

### ISSUE THREAD

**Issue by gabu69** [Automattic/fb-instant-articles#640]
Just to mention and plan ahead, this is a major thing to consider implementing in the next update:
https://media.fb.com/2017/03/09/instant-articles-more-monetization-control-and-flexibility/

> To allow publishers to better customize ads experiences at the article level, we’re making improvements to our Automatic Ads Placement feature and introducing flexibility so that ads can be placed more frequently in articles, now up to every 250 words (previously every 350 words). Publishers can place ads manually within the article or choose between three options for automatic placement: ads every 250, 350 or 500 words. These updates will be available next week.

**Comment by gabu69** [comment]
Any feedback on this? For the sites that rely on monetization this is a major importance as well

**Comment by timjacobi** [comment]
I assume you are talking about [this](https://developers.facebook.com/docs/instant-articles/monetization/ad-placement/). It's a very good point you are making. I will add this as a feature request.
