### ISSUE TITLE
Support Tumblr oEmbed by default

### ISSUE THREAD

**Issue by jerclarke** [Automattic/fb-instant-articles#651]
Tumblr URL in post:

`[embed]http://globalvoices.tumblr.com/post/157945851862/walking-on-death-along-the-iraqi-border[/embed]
`

Works fine on desktop and in our responsive theme. iA chokes:

> No rules defined for `<div class="tumblr-post">` in the context of InstantArticle

The output in the `Source Markup` box:

```
<div class="tumblr-post" data-href="https://embed.tumblr.com/embed/post/6wkVzKPAhRSFMH8MiocWsg/157945851862" data-did="eaa97482c779215de11fda587b68d4b241c28a73"  ><a href="http://globalvoices.tumblr.com/post/157945851862/walking-on-death-along-the-iraqi-border">http://globalvoices.tumblr.com/post/157945851862/walking-on-death-along-the-iraqi-border</a></div>
<p><script async src="https://assets.tumblr.com/post.js"></script></p>
```

Minimum it would be good to have the solution available here, really I hope a fix can be added to the plugin.

**Comment by jeremyclarke** [comment]
Any feedback on this???

Plans to support Tumblr embeds with this plugin? Ideas for transformations that could let the iframe get loaded? It's an iframe in the end, we just need to trick iA into letting it get to that point.

**Comment by timjacobi** [comment]
Duplicate of #582

**Comment by jeremyclarke** [comment]
Not a duplicate. This is a specific issue about whether to support tumblr by default or not. It needs a decision not to be lumped together with random divs output by random plugins.

**Comment by timjacobi** [comment]
That makes sense @jeremyclarke. I will reopen and change to _feature request_.

**Comment by robbiet480** [comment]
This rule appears to work for me given the following Tumblr embed:

```html
<div class="tumblr-post" data-href="https://embed.tumblr.com/embed/post/adrq75eXeB91cB7ng0Mcqw/166715843481" data-did="e71a3c68b404e97971ad20377fc6d308cf9c1079">
  <a href="http://theblacknerd.tumblr.com/post/166715843481/today-i-formally-put-in-my-two-weeks-at-starbucks">http://theblacknerd.tumblr.com/post/166715843481/today-i-formally-put-in-my-two-weeks-at-starbucks</a>
</div>
<script async src="https://assets.tumblr.com/post.js"></script>
```

```json
{
  "class": "InteractiveRule",
  "selector": "div.tumblr-post",
  "properties": {
    "interactive.iframe": {
      "type": "multiple",
      "children": [
        {
          "type": "element",
          "selector": "div.tumblr-post"
        },
        {
          "type": "next-sibling-element-of",
          "selector": "div.tumblr-post",
          "sibling.selector": "script"
        }
      ]
    }
  }
}
```

**Comment by pestevez** [comment]
Hey @jeremyclarke - the solution proposed by @robbiet480 works well for me. It is similar to the one I proposed in #814 for Twitter.
