### ISSUE TITLE
Can I change the order of the elements?

### ISSUE THREAD

**Issue by bryan3561** [Automattic/fb-instant-articles#673]
# I have these items that I add to my article using filters:

- object(Facebook\InstantArticles\Elements\Interactive)
- object(Facebook\InstantArticles\Elements\RelatedArticles)

But I want to change one of them to another place in the article

# Expected Result
Interactive
Paragraph
**RelatedArticles**
Paragraph
Paragraph
Analytics
Interactive

# Actual Result
Interactive
Paragraph
Paragraph
Paragraph
Analytics
Interactive
**RelatedArticles**

---

**Version Info**

* Plugin version: 3.3.3
* WordPress version: 4.7.4
* PHP version: 5.4.28

**Comment by timjacobi** [comment]
Unfortunately this is currently not supported.
