### ISSUE TITLE
Constructors assign to unused dynamic property

### ISSUE THREAD

**Issue by vkama** [Automattic/fb-instant-articles#683]
The constructor of Instant_Articles_Option_FB_Page in wizard/class-instant-articles-option-fb-page.php seems to be bugged:

```PHP
	public function __construct() {
		$this->options_manager = new parent(
			self::OPTION_KEY,
			self::$sections,
			self::$fields
		);
	}
```

most likely the correct is:

```PHP
	public function __construct() {
		parent::__construct(
			self::OPTION_KEY,
			self::$sections,
			self::$fields
		);
	}
```

need to investigate

**Comment by GaryJones** [comment]
This looks like a good catch - the [bit you highlighted](https://github.com/Automattic/fb-instant-articles/blob/da073ea997276aaa8cc3f70243f8c2428c7db916/wizard/class-instant-articles-option-fb-page.php#L40), and [here](https://github.com/Automattic/fb-instant-articles/blob/da073ea997276aaa8cc3f70243f8c2428c7db916/wizard/class-instant-articles-option-fb-page.php#L40) as well.

Under PHP 8.2, I think this would throw dynamic property deprecation notices, so it need to be addressed.
