### ISSUE TITLE
instant articles submission id missing in postmeta

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/fb-instant-articles#711]
After updating to version 4, the plugin is no longer setting a meta value for `instant_articles_submission_id`, yet there are instant articles being submitted successfully to FB.

Not sure if this is a bug or a change in functionality to no longer use that ID in the postmeta table, but I'm doing a query directly in MySQL and noticed that it stopped being set for articles after I updated to v4.

**Comment by diegoquinteiro** [comment]
Hi @kevinlisota,

We're not submitting anything through the API with this new version. We're using a meta tag to tell Facebook to ingest the Instant Article at the time of sharing. We do send a request to force a re-scrape of the article when you edit/save it, so there should be no difference in the overall behavior of the plugin.

Were you using such ID for something?

Thank you,
Diego

**Comment by kevinlisota** [comment]
Aha. I wasn't using the ID, just noticed its absence, and didn't realize that the plugin now skips the API entirely in favor of scraping at the time of a share. Definitely needs some new documentation on this.

Is this correct? When an article successfully gets through IA transformation it outputs the is markup_url tag? Then when a user shares the article for the first time, FB will scrape the markup and ingest it? If an article fails IA transformation, the markup tag is not output and nothing special happens on sharing?

Sounds like you ping the scraper to re-visit on post edits. Does the ingestion happen at the time of publish or at the first sharing? 

How is the post deleted if it is trashed or made private if the API is not being used?
