### ISSUE TITLE
Duplicate update_meta_cache queries

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/fb-instant-articles#713]
With the latest 4.0.2 update, looks like there are now duplicate calls to update_meta_cache being made, resulting in a duplicate query during page load. One call comes from Core, the other from fb-instant-articles.

Duplicate query looks like this as a result of two calls to `update_meta_cache()`
```
SELECT post_id, meta_key, meta_value
FROM gw_wp_postmeta
WHERE post_id IN (12345)
ORDER BY meta_id ASC
```

**Comment by diegoquinteiro** [comment]
We never call this method directly on the code, but 4.0.2 removes a lot of processing by caching some calculations on post meta, so we call get_post_meta when rendering, which might be causing the double query. I'll investigate why this is happening.

Thanks for reporting!
