### ISSUE TITLE
Add a <meta> tag in the Instant Article

### ISSUE THREAD

**Issue by masterfordev** [Automattic/fb-instant-articles#718]
# Steps required to reproduce the problem

1. Install Plugin
2. Sync With Page
3. Publish Post

# Expected Result

* Add a "`<meta>`" tag in the Instant Article with the value i want.

# Actual Result

* Default "`<meta>`" tags.

---

**Version Info**
Lastest.
* Plugin version: 
* WordPress version: 4.8
* PHP version:

**Comment by autoreaction** [comment]
Yeah need some steps to add custom meta tag!!

**Comment by mrgrupbg** [comment]
Yes, I want to know this too also!
