### ISSUE TITLE
Post Excerpt is not in source markup (and not rendered in IA either)

### ISSUE THREAD

**Issue by Djiit** [Automattic/fb-instant-articles#735]
# Steps required to reproduce the problem

1. Write an article and save it.
2. Toggle debug information; the excerpt is not in the source markup.
3. 

# Expected Result

* It should display the post excerpt at least in the source markup. Then users will be able to write their own custom rule.

# Actual Result

* The post excerpt is not in the source markup nor in the transformed markup.

---

**Version Info**

* Plugin version: 4.0.3
* WordPress version: 4.8
* PHP version: 7.0

**Comment by Djiit** [comment]
FYI I tried the following rule, with a custom selector targeting my excerpt : 
```json
{
    "class": "HeaderSubTitleRule",
    "selector": ".myexcerptclass"
}
```

**Comment by timjacobi** [comment]
The plugin only operates on the post content. The excerpt is not part of the post and therefore does not appear in the source markup. I will add this as a feature request.
