### ISSUE TITLE
issue to submit all articles to facebook instant articles

### ISSUE THREAD

**Issue by ciyaye** [Automattic/fb-instant-articles#757]
# Steps required to reproduce the problem

1. Enable Quick Adsense
2. add google code adsense
3. 

# Expected Result

* 

# Actual Result
i can not display google adsnese and i have many issue  and i don know how i solve it 
* 

---

**Version Info**

* Plugin version: Instant Articles for WP 4.0.5
* WordPress version: 4.8.1
* PHP version: 7.x

**Comment by ciyaye** [comment]
No rules defined for <ins class="adsbygoogle"> in the context of InstantArticle
No rules defined for <ins class="adsbygoogle"> in the context of InstantArticle
No rules defined for <div class="_h8t"> in the context of InstantArticle
No rules defined for <ins class="adsbygoogle"> in the context of InstantArticle
No rules defined for <ins class="adsbygoogle"> in the context of InstantArticle

**Comment by onlinetushar** [comment]
Facing same issue
