### ISSUE TITLE
Add option to disable plugin for a single post

### ISSUE THREAD

**Issue by timjacobi** [Automattic/fb-instant-articles#773]
As requested in #567 it would be great if we could allow people disable publishing on a per article basis. A checkbox should be enough.

**Comment by webgrafia** [comment]
any news?

**Comment by timjacobi** [comment]
Momentarily we are focused on fixing bugs and will prioritise feature requests after.

**Comment by webgrafia** [comment]
Thanks timjacobi
in the meantime I discovered instant_articles_should_submit_post filter, that can be used to add a metabox to control single article. Example:
```

add_filter("instant_articles_should_submit_post", "my_instant_articles_should_submit_post",10, 2);
function my_instant_articles_should_submit_post($should_show, $IA_object){
    if($should_show){
    . . . 
    // get post meta managed by metabox
    if(get_post_meta($IA_object->get_the_id(), "enable_ia"))
        return true
    }
    return false;
}

```

**Comment by timjacobi** [comment]
Feel free to submit a PR and I’ll review it :-)

**Comment by paulschreiber** [comment]
Working on this.

**Comment by Sazarimma** [comment]
> Thanks timjacobi
> in the meantime I discovered instant_articles_should_submit_post filter, that can be used to add a metabox to control single article. Example:
> 
> ```
> 
> add_filter("instant_articles_should_submit_post", "my_instant_articles_should_submit_post",10, 2);
> function my_instant_articles_should_submit_post($should_show, $IA_object){
>     if($should_show){
>     . . . 
>     // get post meta managed by metabox
>     if(get_post_meta($IA_object->get_the_id(), "enable_ia"))
>         return true
>     }
>     return false;
> }
> ```

Hi,
Is this still valid to exclude single post? So, I can use this code to exclude any post to FBIA?
I am looking for a solution to exclude single post of FBIA.
Hopefully, someone will guide me. TQVM

**Comment by paulschreiber** [comment]
@Sazarimma see my pull request (#1011) which provides this feature.

**Comment by Sazarimma** [comment]
Hi @Paul Schreiber, Thank you so much for your help. I am not sure how to implement this since its so confusing me and I am beginner. I want to know which one is correct.

I have to edit this one only right? > class-instant-articles-publish-meta-box.php based on this > a[dd metabox action to toggle publish status](https://github.com/Automattic/facebook-instant-articles-wp/pull/1011/commits/3c10345c0e723ddd052c257cd309dafec5105e61) Am I right?

I'm so sorry for taking your time. I can edit them myself, it just not sure which one and where do I start it first. So, if possible please show me the step. TQVM for help.

**Comment by paulschreiber** [comment]
@Sazarimma you're going to need to find someone who understands how to get a plugin from GitHub and install it on your server to help you out.

**Comment by Sazarimma** [comment]
@paulschreiber No one will help me. But after I read a few articles, I understand that I have to download and upload it to my site. I download the plugin as shown on the image attach here. Is it correct? Currently, I have FBIA original plugin, do I have to remove it or just let it be? Sorry for many question. I want to learn. Thanks for your time.
![zsa](https://user-images.githubusercontent.com/44695464/62672093-de43dd80-b9cb-11e9-8e44-b65d6d100c9a.png)

**Comment by paulschreiber** [comment]
@Sazarimma Yes, you need to remove the original FBIA plugin and replace it with the downloaded version from your screen shot.

**Comment by Sazarimma** [comment]
@paulschreiber THANK YOU SO MUCH. I seriously appreciate it.
