### ISSUE TITLE
Allow ads control on a per-post basis

### ISSUE THREAD

**Issue by bactisme** [Automattic/fb-instant-articles#784]
I produce lot of content, but some contents doesn't comply with the Facebook guidelines for monetization (violent video game reviews, p2p).

I would like to be able to disable monetization on some posts. 

The best could be to have a filter, either on _Instant_Articles_Option::get_option_decoded_, or on _Instant_Articles_Post::add_ads_from_settings_ output. 

It will allow us to plug customization code via filter and control ads more precisely. 

(If some devs validate the best way, I can make a PR)

**Comment by Ulrichfr** [comment]
UP
