### ISSUE TITLE
Support custom Ad sizes

### ISSUE THREAD

**Issue by haneef95** [Automattic/fb-instant-articles#789]
We do not want to have such a big ad, we're preferring a rather smaller ad, we don't have any ad graphics for 320x50 dimension, rather we have 500x90 (equivalent to 320x57.6 OR 277.78x50).

# Steps required to reproduce the problem

1. Goto http://yourdomain.com/wp-admin/admin.php?page=instant-articles-wizard
2. Select Ads type: Custom Embed code
3. In the embed code box, paste:
`<iframe src="https://yourdomain.com/?p=12345" width="500" height="90"></iframe>`
4. Goto https://yourdomain.com/feed/instant-articles
5. You'll see two nested iframes like so:
`<figure class="op-ad"><iframe width="300" height="250"><iframe src="https://yourdomain.com/?p=27671" width="500" height="90"></iframe></iframe></figure>`

# Expected Result

* Only one iframe with 500x90 dimension

# Actual Result

* Two nested iframes, the parent iframe is smaller than the child iframe.

---

**Version Info**

* Plugin version: 4.0.5
* WordPress version: 4.8.2
* PHP version: 7.0.24

**Comment by pestevez** [comment]
I am able to repro, but I think this issue should be treated as a feature request. What do you think, @timjacobi?

It looks like the current implementation for `Custom Embed Code` type of Ad only supports one of the two available sizes (300 x 250 or 320 x 50), and will set the selected value as dimensions for the `iframe` inside the `figure`, and then will add the custom embed code as a child of the iframe.

My proposal is to add a feature request to support custom Ad sizes.

**Comment by timjacobi** [comment]
I agree

**Comment by pestevez** [comment]
Hey @haneef95, thanks for flagging this issue. Momentarily we are focused on fixing bugs and will prioritize feature requests after. Feel free to submit a PR though.
