### ISSUE TITLE
Missing YouTube video

### ISSUE THREAD

**Issue by Sukhwinder500** [Automattic/fb-instant-articles#790]
# Steps required to reproduce the problem
hello i embed youtube videos on my website www.onlinetvstar.com but when i submit request for Facebook Instant Article then its rejected and give issue. Please help me for this.
1. Add Text or Images (Missing)
2. Social Embeds
3. Videos not shown on my Facebook Page Manager App. its Like the videos or images which are uploaded by the help of Plugin its not shown on this. Like Plugin not worked on Fb Instant Article.

# Expected Result

* Let me Know the solution and want to connect my website.

# Actual Result

* 

--- check Attachment 
![rejected](https://user-images.githubusercontent.com/32815650/31930102-2224bc08-b8bc-11e7-8f0a-1cd9f6a62a82.jpg)

**Version Info**

* Plugin version: 

* WordPress version: 4.4.6
* PHP version:

**Comment by pestevez** [comment]
Hi @Sukhwinder500, please share:
- The version of the plugin you are using
- The URLs of the articles you submitted to the reviewers
- The _Source Markup_ and _Transformed Markup_ for some of the articles the reviewers mention. which you can find them the Instant Article plugin section when you edit a post (click on _[Toggle debug information]_)

**Comment by Sukhwinder500** [comment]
Hello @pestevez 

- Plugin Version - 4.0.5

- Url - http://onlinetvstar.com/hes-not-stopping-throwback-fails-november-2017/ or more on www.onlinetvstar.com

- Source markup -  <p>We&#8217;re taking it back to a simpler time, when people were failing all the time&#8230; Wait. Anyway, here&#8217;s some hilarious throwback fails for you to enjoy, we&#8217;ve got some hilarious wipeouts, a mulligan master, and a truck out of control. Have a favorite? Let us know in the comments below!! </p>

- Transformed Markup - <html>
  <head>
    <link rel="canonical" href="http://onlinetvstar.com/hes-not-stopping-throwback-fails-november-2017/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.6.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.0.5"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.6.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="http://onlinetvstar.com/wp-content/uploads/2017/11/Hes-Not-Stopping-Throwback-Fails-November-2017-FailArmy.jpeg"/>
        </figure>
        <h1>He’s Not Stopping!!: Throwback Fails (November 2017)</h1>
        <time class="op-published" datetime="2017-11-05T11:32:08+00:00">November 5th, 11:32am</time>
        <time class="op-modified" datetime="2017-11-05T11:32:08+00:00">November 5th, 11:32am</time>
        <address><a>admin</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=117829105565616_117829118898948&amp;adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>We’re taking it back to a simpler time, when people were failing all the time… Wait. Anyway, here’s some hilarious throwback fails for you to enjoy, we’ve got some hilarious wipeouts, a mulligan master, and a truck out of control. Have a favorite? Let us know in the comments below!! </p>
      <footer>
        <small>All Rights Reserved, 2017</small>
      </footer>
    </article>
  </body>
</html>

Please help me to solve this issue
thanks for ur Reply..

**Comment by pestevez** [comment]
How are you embedding the YouTube video? Is it through a third-party plugin? I don't see the YouTube embed code in your Sorce Markup.

Since the YouTube embed code is not available to the plugin, then it does not get added to the Instant Article. That's the reason you are getting rejected in the review process because you are missing elements.

**Comment by humgurung** [comment]
Hi @pestevez - It means though we embed Youtube video in our WordPress site FB Instant Articles do not add and display, right? What else could be the work around to display?

**Comment by pestevez** [comment]
The part I am missing is how are you adding the YouTube video to your posts? Is it through a third party plugin? The Instant Articles plugin uses the source markup available, so if the YouTube video tags are not there, we will miss it. An option will be looking at other places beyond the source markup, that's why I want to understand your publishing flow.

**Comment by Sukhwinder500** [comment]
hi @pestevez  m using " Viduze Wordpress Theme "  and its default please check the images

1. how i copied a youtube video link
![git 1](https://user-images.githubusercontent.com/32815650/32957638-4fcc0fce-cbe2-11e7-962c-399640f9b9c9.jpg)

2. Paste 1st in Box for thumbnail for the post " using FEATURED VIDEO PLUS " Plugin.
![git 2](https://user-images.githubusercontent.com/32815650/32957698-81a81d1c-cbe2-11e7-96bd-8e5c7426b22d.jpg)

3. 2nd Paste in this box for Video Player
![git 3](https://user-images.githubusercontent.com/32815650/32957737-99824ef8-cbe2-11e7-83fb-de9d91d7647b.jpg)

Website :- www.onlinetvstar.com
wordpress version :- 4.4.6

Regards

**Comment by pestevez** [comment]
Thanks for the information, @Sukhwinder500. Our team will prioritize your feature request.

**Comment by humgurung** [comment]
@pestevez - my case is little different than @Sukhwinder500 I simple copy the Youtube video link like above and paste it to post without any embed code as WordPress render the responsive video. Am I missing anything here?

**Comment by pestevez** [comment]
@humgurung - please check #697, #556 and #761 to see if it is any of the existing issues. If not, can you please create a separate issue so we can better track it?

**Comment by rbacarin** [comment]
Hi @pestevez are there any update about @Sukhwinder500 feature request ? I got the same need =)

**Comment by Sukhwinder500** [comment]
@rbacarin hello not any update?

**Comment by pestevez** [comment]
Sorry, no updates, however, I believe we will tackle bug fixes first.

Also, in this particular case, I am not even sure if this will be a third-party integration that we will support. While the Instant Articles format supports videos in the header, they have to be a [Video](https://developers.facebook.com/docs/instant-articles/reference/video) element; and YouTube (and other third-party video players) are supported using [Embeds](https://developers.facebook.com/docs/instant-articles/reference/embeds), which cannot appear in the article [Header](https://developers.facebook.com/docs/instant-articles/reference/cover).

In any case, please feel free to submit a PR and our team will take a look at it.

**Comment by Umedi95** [comment]
![untitled](https://user-images.githubusercontent.com/18601809/43816227-350cdb5c-9b06-11e8-863a-96ca67f644f1.png)

i dont understant what they mean by saying this error, it says embed from acctual article is not showing in facebook instant article, but in facebook page app i can see it. and about that img shodnt be enclosed with p
