### ISSUE TITLE
Editor roles can't access Instant Article Wizard Page.

### ISSUE THREAD

**Issue by maungthuu** [Automattic/fb-instant-articles#841]
For some reasons , I need to make sure Editor Roles can access Instant Article Wizard Page. 

domain.com/wp-admin/admin.php?page=instant-articles-wizard

But default is admin roles can only access this page.
How can i give permission editor roles to access this page.

I tried to do with Members Plugin .

https://wordpress.org/plugins/members/

Thanks

**Comment by vkama** [comment]
Maybe you can try adding 'manage_options' to the Editor role with that plugin?

Let me know if it worked. Thanks

**Comment by maungthuu** [comment]
For now , I added 'manage_options'. This worked as temporary fix. 
Con : This enable all other options page of Theme and Plugins for editors  roles. 
I think Instant Article Plugin should have its own permission to access IA Option Page.

Thanks.
