### ISSUE TITLE
mysql down

### ISSUE THREAD

**Issue by lubimow** [Automattic/fb-instant-articles#845]
I often began to fall down mysql. I recorded a large number of requests:
```sql
`11022 database       localhost user      20888  Query  Waiting INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('_transient_timeout_instantarticles_mod_19499', '1514767515', 'no') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`o`
```
## Version Info

* Plugin version: 4.0.6
* WordPress version:  4.9.1
* PHP version: 5.7

**Comment by diegoquinteiro** [comment]
Thanks @lubimow for reaching out! I'll investigate and reach back to you. It seems related to #713.

**Comment by lubimow** [comment]
@diegoquinteiro see my logs: https://www.dropbox.com/s/pzn1c2s0e8bucph/error.rtf?dl=0 and https://www.dropbox.com/s/974h410iaa9mblk/slow.rtf?dl=0
