### ISSUE TITLE
you should add data-src transformation rule by default

### ISSUE THREAD

**Issue by theblackdie** [Automattic/fb-instant-articles#867]
I am using wordpress 4.9.2 with PHP7 

I realized that some images are treated as img data-src=”blablabla” instead of img src=”blablabla”

That’s weired. 

But I added the custom transformation rule:
{
“class”: “ImageRule”,
“selector” : “img[data-src]”,
“properties” : {
“image.url” : {
“type” : “string”,
“selector” : “img”,
“attribute”: “data-src”
}
}

at the end of the json file.

And Eureka. It worked!! after 70 tries for more than 3 days

**Comment by vkama** [comment]
Can you provide the piece of HTML that was giving you trouble?

Thanks

**Comment by theblackdie** [comment]
<p>امتلاك شعر جميل طويل، قوي ولامع، هو أمنية نتشاركها كلنا. لسوء الحظ، يعاني الكثيرون من تساقط الشعر، من الشعر الرمادي ومن أطراف شعر متكسرة…لكن لنر ما الذي يمكن أن يسبب هذه المشاكل وكيف يمكن أن نعالجها !</p>
<h4>عملية التغيير الطبيعية</h4>
<p>يبدأ الشعر الأبيض بالظهور عندما تتوقف الخلايا الصباغية المسؤولة عن الشعر</a> melanocytes، عن إفراز الميلانين.<br />
مثال على ذلك الشعر الأشقر، الناتج عن إنتاج الخلايا الصباغية للقليل من الميلانين، بعكس الشعر الأسود الذي هو نتيجة الإفراز الكبير لهذه الخلايا.</p>
<p>عندما تُستنفد كمية هذه المادة، يتحول لون الشعر إلى الأبيض. وهنا يجب أن نتوقف عند نقطة مهمة حول تسمية &#8220;الشعر الرمادي&#8221;. مع أن هذا التعبير مستخدم كثيراً، لكنه ليس دقيقاً، لأن اللون أكثر بياضاً من الرمادي، وهو غالباً نتيجة اختلاط الشعر الأبيض مع الألوان الأخرى.</p>
<h4>ما الذي يعطي هذا اللون لشعركم</h4>
<p>لغاية اللحظة، لا يمكننا أن نحدد السبب الدقيق للشيب، وليس هناك إجماع في الأوساط العلمية حول هذا الموضوع. لكن ما هو أكيد، أن العامل الوراثي يلعب دوراً حاسماً في هذه العملية.</p>
<p>قد يسارع الضغط النفسي أو الصدمات الأخرى في ظهور الشعر الأبيض، مع أن العلماء لا يعرفون لأي درجة قد يؤثر هذا. لكن، لحسن الحظ، هناك وسائل طبيعية لتحسين صحة الشعر واستعادة لونه الطبيعي.</p>
<h3>ماسك طبيعي لتقوية الشعر وجعله أجمل</h3>
<h4>المكونات :</h4>
<ul>
<li>3 سنتم من جذر الزنجبيل</li>
<li>ملعقة كبيرة من العسل</li>
<li>ملعقة كبيرة من زيت الزيتون</li>
</ul>
<h4>طريقة التحضير والاستخدام :</h4>
<ul>
<li>خذوا جذر الزنجبيل وابشروا منه قطعة بطول 3 سنتم، ثم أضيفوا إليه زيت الزيتون والعسل، وامزجوا بعناية.</li>
<li>ضعوا المزيج على شعركم المبلل واتركوه يتفاعل مدة 40 دقيقة قبل أن تغسلوه كالمعتاد. استعملوا هذه الوصفة مرة واحدة في الأسبوع.</li>
</ul>
<p>&nbsp;</p>
<p><img src="http://holoulzakia.com/wp-content/uploads/2018/01/file.jpg" alt="" width="1024" height="700" /></p>
<h4>خلطة طبيعية للشعر الأبيض</h4>
<h4>المكونات :</h4>
<ul>
<li>ملعقة كبيرة من زيت الحبة السوداء (حبة البركة)</li>
<li>ملعقة كبيرة من زيت الزيتون</li>
</ul>
<p><img  data-src="http://holoulzakia.com/wp-content/uploads/2018/01/blackseed-1.jpg" /></p>
<h3>طريقة التحضير والاستخدام :</h3>
<ul>
<li>امزجوا الزيتين في وعاء صغير ثم ضعوا المزيج على كامل شعركم، وكذلك على فروة شعركم عن طريق تدليكه.</li>
<li>اتركوه مدة ساعة، ثم اغسلوه بالماء الفاتر.</li>
<li>عليكم أن تستعملوا هذه الخلطة كل يوم مدة أسبوع، وبعدها تكفي 3 مرات في الأسبوع للحصول على النتيجة المتوخاة.</li>
</ul>
<h4>إليكم في هذا الفيديو وصقة تُنقذ حياتك</h4>
<div class="embed"><iframe width="1170" height="878" src="https://www.youtube.com/embed/RO_ftE1tfbA?start=6&#038;feature=oembed" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>

**Comment by vkama** [comment]
Just to be clear, you have no plugins that create <img> tags? This is a new behaviour of WP 4.9.2?

Thanks

**Comment by theblackdie** [comment]
part of the them I am using (publisher theme) have lazy loading 
this feature is adding the tag named data-src
that's not a new behaviour of WP
