### ISSUE TITLE
Notice: Undefined index: page_id in wp-content\plugins\fb-instant-articles\facebook-instant-articles.php on line 107

### ISSUE THREAD

**Issue by markbarnes** [Automattic/fb-instant-articles#872]
## Steps required to reproduce the problem
1. Visit wp-admin/plugins.php before you set up Instant Articles.

## Expected Result
No PHP notice.

## Actual Result 
Notice: Undefined index: page_id in wp-content\plugins\fb-instant-articles\facebook-instant-articles.php on line 107

## Version Info
* Plugin version: 4.0.6
* WordPress version: 4.9.2
* PHP version: 5.6.25

The error occurs because get_option('instant-articles-option-fb-page') returns the string '[]' rather than an array with the index 'page_id'.

**Comment by GaryJones** [comment]
Fixed in d56c04ae63c3dcd70993eca40c5e986890892548.
