### ISSUE TITLE
PHP 7.1 Compatibility 

### ISSUE THREAD

**Issue by trepmal** [Automattic/fb-instant-articles#874]
Since PHP 7.1, passing [too few arguments will cause a fatal error](http://php.net/manual/en/migration71.incompatible.php#migration71.incompatible.too-few-arguments-exception)

I've flagged two occurrences of `disabled()` which should pass at least [one argument](https://github.com/WordPress/WordPress/blob/39ce01d83a0bfc06c278d7a0cc098be508fe7f6e/wp-includes/general-template.php#L4327)

 - https://github.com/Automattic/facebook-instant-articles-wp/blob/0bd3899ca4cc5e2bba212ecf30d4d8a733ba0541/wizard/class-instant-articles-option.php#L285
 - https://github.com/Automattic/facebook-instant-articles-wp/blob/0bd3899ca4cc5e2bba212ecf30d4d8a733ba0541/wizard/class-instant-articles-option.php#L359

**Comment by zomidaily** [comment]
Is this plugin compatible with PHP 7.1 yet? Regards,

**Comment by GaryJones** [comment]
> Is this plugin compatible with PHP 7.1 yet?

Yes 😄 (at least the `develop` branch, and the first release after 5.0.0, make it so.)
