### ISSUE TITLE
problem with lazy load

### ISSUE THREAD

**Issue by lubimow** [Automattic/fb-instant-articles#877]
I'm using the Wp-rocket plugin. When I enabled lazy-load, images in the article instant articles began to appear in this form:   

` <img src="data:image/gif;base64,R0lGODdhAQABAPAAAP///wAAACwAAAAAAQABAEACAkQBADs="/>`

How can I fix this?

## Version Info

* Plugin version:  4.0.6 
* WordPress version: 4.9.4
* PHP version: 7.1

**Comment by pestevez** [comment]
Hi @lubimow, thanks for reporting this issue. Since this is related to compatibility with a third-party plugin, our team will treat it as a feature request, so it will be prioritized with the rest of requests.

**Comment by arunbasillal** [comment]
Hey guys, 

I am Arun Basil Lal, I work for WP Rocket and I just wanted to share couple of insights. 

WP Rocket already has checks in place to disable LazyLoading on feeds and doesn't show up on the default WordPress feeds. Here is the part of the code that corresponds to it: https://github.com/wp-media/wp-rocket/blob/master/inc/front/lazyload.php#L139

If you have any questions related to it, please do not hesitate to let us know. 

Best regards.

**Comment by lubimow** [comment]
@pestevez Please read the comment above

**Comment by maungthuu** [comment]
Hi @lubimow 
 
Put this code in Custom Transformer Rules. 

`{
    "rules": [{
        "class": "ImageRule",
        "selector": "img[data-src]",
        "properties": {
            "image.url": {
                "type": "string",
                "selector": "img",
                "attribute": "data-src"
            }
        }
    }]
}`

**Comment by lubimow** [comment]
@maungthuu Thanks, this solved my problem

**Comment by maungthuu** [comment]
@lubimow glad it helps.

**Comment by Singletrackmark** [comment]
We have the same problem. I've added the custom rule above to our IA plugin. Do I have to go back and republish all affected articles now?

**Comment by maungthuu** [comment]
@Singletrackmark you need to update affected articles again.

**Comment by lubimow** [comment]
@maungthuu Hey. I again do not see a link to the image. Help, what to do?
