### ISSUE TITLE
How to put RSS feed text on footer of the content?

### ISSUE THREAD

**Issue by maungthuu** [Automattic/fb-instant-articles#890]
Hello all,

I'm finding a method to put this RSS text on the footer of every post in Instant Article. Please see the attachment.
![content-feed](https://user-images.githubusercontent.com/11045808/36949117-72a89876-2012-11e8-9aff-59ef92129fff.png)

Thanks

**Comment by maungthuu** [comment]
Hi @mburak 

For temporary, I just added main website link instead of post url link in footer credit section.
It'll be awesome if we can add dynamic post url in the footer section.

Thanks

**Comment by jerclarke** [comment]
FWIW this is possible using the [WP Filter API](https://developer.wordpress.org/reference/functions/add_filter/#more-information) and the `instant_articles_content` filter in this plugin. 

We use code similar to below to insert our author credits at the bottom of the post:

```PHP
/**
 * Filter for Facebook Instant Articles that adds HTML to the end of the post content
 *
 * @param string $content Default IA content that would have been used
 * @param int    $post_id ID of the post 
 *
 * @return string New IA content that will be used 
 */
function ticket_890_filter_instant_articles_add_footer($content, $post_id) {
	/**
	 * Get the post object if you need it
	 */
	$post = WP_Post::get_instance($post_id);

	$content = "SOMETHING BEFORE CONTENT" . $content . "SOMETHING AFTER CONTENT";

	return $content;
}
add_filter('instant_articles_content', 'ticket_890_filter_instant_articles_add_footer', 10, 2);
```

Be very careful though, you need to ensure all the code you add is up to the IA spect. For example we used `<footer>` to wrap our content, but that required adding the following Transformation Rules to our JSON (we use PHP to control Transformations, but you can get the idea if you understand how the Transformations JSON works): 

```PHP
array(
	'class' => 'FooterRule',
	'selector' => 'footer',
),
array(
	'class' => 'ParagraphFooterRule',
	'selector' => 'footer p',
),
```
