### ISSUE TITLE
Instant Article Mass Update Issue

### ISSUE THREAD

**Issue by bsgies** [Automattic/fb-instant-articles#893]
Hi everyone,

I have made some changes in IA’s setting like I’ve embedded a new tracking script. Now what has already been scraped by Facebook doesn’t have my new tracking code in its source code. The only option left is to open WordPress post one by one and click update so that a newer version can be sent to Facebook via RSS. Is there any quicker way I can send the new version of all my blog posts to Facebook in one go?

Thanks.

**Comment by mburak** [comment]
Hey @bsgies, this would be a great addition to the plugin! Unfortunately we cannot do bulk updates at the moment. We are a implementing some features that would help to add this functionality in the future. 
In the meantime what you can try is to use some Wordpress bulk-update plugin to update the modified time for the posts so the next time the RSS is fetched it would re-scrape all the articles.

**Comment by maungthuu** [comment]
Hi @bsgies 

You can bulk update posts from Wordpress>Posts.

Select Posts you want to edit > Select Edit  > and Just click Update Button.

It's done.
