### ISSUE TITLE
No rules defined for <aside class="mashsb-container mashsb-main mashsb-stretched"> in the context of InstantArticle

### ISSUE THREAD

**Issue by BabysMutu** [Automattic/fb-instant-articles#900]
Hi, i like mashshare plugin but after insteling this plusgin i fount error on InstantArticle when i try to post upadte the i got error like this - No rules defined for <aside class="mashsb-container mashsb-main mashsb-stretched"> in the context of InstantArticle  

Submit this article even with warnings  | can i submit this artilcle by checking this or need to fix please help !

thank you

**Comment by jerclarke** [comment]
You need to learn to use IA  [Transformations](https://developers.facebook.com/docs/instant-articles/sdk/transformer-rules) to tell IA what to do with the `aside.mashsb-container` HTML. This is very complicated. 

Here's an example ticket where I include the solution to a similar problem: #732 

Related ticket about making support for custom HTML via. IA Trasformations easier to accomplish: #897
