### ISSUE TITLE
No rules defined for <pre class="brush: java; title: ; notranslate"> in the context of InstantArticle 

### ISSUE THREAD

**Issue by ghost** [Automattic/fb-instant-articles#914]
i am using instant article plugin in my wordpress blog and i am using syntaxHighlighter plugin to decorate my source code so that user can read it easily but when i write my code inside [java]mycode[/java, instant article plugin shows this error "No rules defined for `<pre class="brush: java; title: ; notranslate">` in the context of InstantArticle" how to solve this please help me :)

**Comment by pestevez** [comment]
Hi @ranbahadurbk. This is covered in the Frequently Asked Questions section of the [readme](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/README.md). Can you please check there under **What does the “No rules defined for ____ in the context of ____” warning mean?**
