### ISSUE TITLE
Instant Articles Configuration problem

### ISSUE THREAD

**Issue by Ironir** [Automattic/fb-instant-articles#915]
Hello, I have a problem with the instant articles configuration, I submitted the articles for review, but it says that my articles contain visible code.

![screenshot_8](https://user-images.githubusercontent.com/34078470/38421978-5feaf21e-39a9-11e8-9b7f-c23cdd38bce2.jpg)

![screenshot_9](https://user-images.githubusercontent.com/34078470/38421979-600aab4a-39a9-11e8-87b9-081839b12d6a.jpg)

What should I do to fix these problems? I don't use visible code just the normal symbols like ( . , ; <>) ?

**Comment by pestevez** [comment]
Hey @Ironir. Can you please share the Source and Transformed markup for any of those articles? The Frequently Asked Questions of the [readme](https://github.com/Automattic/facebook-instant-articles-wp/blob/master/README.md) has some instructions on how to do it.

Also, can you please share which version of the plugin you are using?

By the way, based on the screenshot, it looks like the main reason for the rejection is that you have not customized the default style.

**Comment by Ironir** [comment]
Hey @pestevez I'm not sure what are you asking for but hope this is it 
![screenshot_14](https://user-images.githubusercontent.com/34078470/38424566-c0fe4e18-39b1-11e8-85b6-0eb3c72181ef.jpg)
The plugin is the latest version Version 4.0.6. 
Yeah I created my own style before I applied, but now I deleted it and only uploaded the logo to the default style... could this be the reason?

**Comment by diegoquinteiro** [comment]
Hi @Ironir, please follow these instructions to get the information we need for debugging:

* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

@abramova2018 please open a new issue explaining your problem with the plugin in detail so we can debug.

@Hamza4332 you need to be approved (by using up to the 8 URLs you already claimed) by our review team before you are able to claim all your other URLs.

Thank you,
Diego

**Comment by Ironir** [comment]
@diegoquinteiro thank you for your response, here: 
![screenshot_1](https://user-images.githubusercontent.com/34078470/38759553-c80c81dc-3f76-11e8-94b3-19f90977d2b9.jpg)
