### ISSUE TITLE
Transformer rule for placing <video> in <header>?

### ISSUE THREAD

**Issue by wle8300** [Automattic/fb-instant-articles#940]
Hi there, I'm looking at the various transformer rules and I don't see one for putting videos into the `<header>`. We'd like to take advantage of the preview videos [as the cover](https://developers.facebook.com/docs/instant-articles/design/videolink)<sup>1</sup> in the NewsFeed and this seems to be necessary to accomplish that.

Any help appreciated! Thx!

1. https://developers.facebook.com/docs/instant-articles/design/videolink

**Comment by Michaelovich** [comment]
@wle8300 Did you figure out how to do this? I'm trying to this aswell.
