### ISSUE TITLE
Instant Article Approval Pending for 15 Days 

### ISSUE THREAD

**Issue by pumamammal** [Automattic/fb-instant-articles#950]
Good day,

I've registered for Applied for Instant Article on my page. This is the 15th day and I haven't gotten reply yet. 

What do you think I should do?

**Comment by gaurav84692** [comment]
same as brother...I've registered for Applied for Instant Article on my page. This is the 30th day but facebook cant reply

**Comment by pumamammal** [comment]
Hello, @gaurav84692 Hope you are good?

please you can contact me through mail lets talk about this experiences with Facebook Instant Article.
pumamammal@gmail.com. I want to ask, When you submitted your Instant Article for review, where you still updating your website such that some articles were not suitable to be published?

**Comment by gaurav84692** [comment]
Thank you so much facebook team for this opportunity. instant article for
review , where all article suitable for instant article ,no
violence contain in www.gujaratnewslive.com.














                    Gaurav Shingala

**Comment by nepali1234** [comment]
i have my pending for 3 month what should i do ?

**Comment by gaurav84692** [comment]
hello..,

Since 3 months ago, I send an appeal to Facebook for approving my instant
article request. and so many times to mail and appeal threw connect with
Facebook team but all time same answer.

I hope, this time good reply... :)














                    Gaurav Shingala

**Comment by nepali1234** [comment]
exactly. i have the same problem. how can i process again. i dont know what to do. my time is wasting anyone help me

**Comment by jerclarke** [comment]
If you want to stop wasting your time I recommend you stop trying to use Instant Articles. 

Instead spend your time optimizing the performance and design of the mobile responsive version of your site. That will help you now and in the future and on all mobile platforms. 

If you are feeling extreme enough you could start serving an AMP version which will be quick on the frontend. 

Instant Articles is a swamp of terrible support. If your site isn't accepted then it's impossible to know if it ever will or could be accepted. Any time you invest is 100% a gamble and they do not in any way offer you accountability for time wasted. 

Good luck, I'm sorry that this is the truth as I and many others here have experienced it. 

SHAME ON FACEBOOK 🤷🏻‍♀️
