### ISSUE TITLE
error while images on wordpress post 

### ISSUE THREAD

**Issue by basudevkunwar** [Automattic/fb-instant-articles#958]
## Steps required to reproduce the problem

1. This post was transformed into an Instant Article with some warnings [Learn more | Transformer rule configuration | Toggle debug information]

**_Invalid selector for fields (image.url). The node being transformed was <img> in the context of InstantArticle within the Rule ImageRule with these properties: { image.url=StringGetter}_**

## Actual Result 
If your issue is about the error message _No rules defined for ..._. Please do the following.
* Go to the Wordpress editor and open the post
* In the Instant Article plugin section click on _[Toggle debug information]_
* Share both _Source Markup_ and _Transformed Markup_

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: Version 4.1.0
* WordPress version: 4.9.6
* PHP version: 5.6.36

Without the above information we are not able to debug the issue and will close it.

**Comment by yeah-sir** [comment]
Hi @basudevkunwar, Can you please add the input and output HTML here as well. That will help us debug this issue better
