### ISSUE TITLE
Please tell Why Its happening ?

### ISSUE THREAD

**Issue by Desitalk** [Automattic/fb-instant-articles#964]
#0 /home/#####/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /home/#####/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home/#####/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home/#####/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(225): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
#4 /home/#####/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /home/#####/public_html/wp-content/plugins/fb-instant-articles/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(367): Facebook\Facebook->sendRequest('POST', '/?id=http%3A%2F...', Array, 'EAACiLR0hYMIBAH...', NULL, NULL)
#6 /home/#####/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(481): Facebook\Facebook->post('/?id=http%3A%2F...', Array, 'EAACiLR0hYMIBAH...')
#7 [internal function]: invalidate_scrape_on_update(173089, Object(WP_Post), Object(WP_Post))
#8 /home/#####/public_html/wp-includes/class-wp-hook.php(286): call_user_func_array('invalidate_scra...', Array)
#9 /home/#####/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#10 /home/#####/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#11 /home/#####/public_html/wp-includes/post.php(3647): do_action('post_updated', 173089, Object(WP_Post), Object(WP_Post))
#12 /home/#####/public_html/wp-includes/post.php(3746): wp_insert_post(Array, false)
#13 /home/#####/public_html/wp-admin/includes/post.php(377): wp_update_post(Array)
#14 /home/#####/public_html/wp-admin/post.php(194): edit_post()
#15 {main}

Warning:  Cannot modify header information - headers already sent by (output started at /home/#####/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php:484) in /home/#####/public_html/wp-admin/post.php on line 198

Warning:  Cannot modify header information - headers already sent by (output started at /home/#####/public_html/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php:484) in /home/#####/public_html/wp-includes/pluggable.php on line 1219

_When Am trying Edit & Update Am Getting These Error's_ **please Tell How its get Resolved ?**

**Comment by yeah-sir** [comment]
Hi @Desitalk can you please attach the input and output HTML with which you are seeing this error? This will help is debug this issue better.

**Comment by Desitalk** [comment]
<html>
  <head>
    <link rel="canonical" href="http:/*Edited*/09/08/173834.php"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.9.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.1.1"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <h1>Auto Draft</h1>
        <time class="op-published" datetime="2018-08-09T12:11:18+05:30">August 9th, 12:11pm</time>
        <time class="op-modified" datetime="2018-08-09T12:11:18+05:30">August 9th, 12:11pm</time>
        <address><a href="*Edited*">News Desk</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=*Edited*&adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <figure class="op-tracker">
        <iframe><script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
 
  ga('create', 'UA-*Edited*', 'auto');
  ga('require', 'displayfeatures');
  ga('set', 'campaignSource', 'Facebook');
  ga('set', 'campaignMedium', 'Social Instant Article');
  ga('set', 'title', 'FBIA: '+ia_document.title);
  ga('send', 'pageview');
 
</script> </iframe>
      </figure>
      <footer>
        <small>*Edited*</small>
      </footer>
    </article>
  </body>
</html>

**Comment by inimist** [comment]
Having same problem when I QuickEdit a wordpress post.

**Comment by Nistelroy78** [comment]
Also had this problem :/

**Comment by atuljha23** [comment]
Having the same..

**Comment by shameeryou** [comment]
I have same issue

#0 /home/fanport/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /home/fanport/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /home/fanport/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /home/fanport/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 0, Array)
#4 /home/fanport/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
#5 /home/fanport/public_html/wp/wp-content/plugins/social-media-auto-publish/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(361): Facebook\Facebook->sendRequest('POST', '/?id=https%3A%2...', Array, 'EAARjkbqobW8BAI...', NULL, 'v2.10')
#6 /home/fanport/public_html/wp/wp-content/plugins/fb-instant-articles/facebook-instant-articles.php(518): Facebook\Facebook->post('/?id=https%3A%2...', Array, 'EAARjkbqobW8BAI...')
#7 /home/fanport/public_html/wp/wp-includes/class-wp-hook.php(288): invalidate_scrape_on_update(132897, Object(WP_Post), Object(WP_Post))
#8 /home/fanport/public_html/wp/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#9 /home/fanport/public_html/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#10 /home/fanport/public_html/wp/wp-includes/post.php(4093): do_action('post_updated', 132897, Object(WP_Post), Object(WP_Post))
#11 /home/fanport/public_html/wp/wp-includes/post.php(4196): wp_insert_post(Array, false)
#12 /home/fanport/public_html/wp/wp-admin/includes/post.php(407): wp_update_post(Array)
#13 /home/fanport/public_html/wp/wp-admin/post.php(219): edit_post()
#14 {main}

Issue started after my facebook account automatically logged out from all devices. 

Im using a social media auto publish along with it. Even If i disable that the issue remains
