### ISSUE TITLE
Website Verification

### ISSUE THREAD

**Issue by asad6351** [Automattic/fb-instant-articles#975]
I am getting this error while trying to submit my website URL
"The provided URL is not being accepted because the site has minimal readership, which violates the Instant Article Policies (https://developers.facebook.com/docs/instant-articles/policy/). Please provide a different URL."

All details explain in this video have a look watch till end
https://youtu.be/558au-1f6us

**Comment by jerclarke** [comment]
Wow there sure were a lot of these that got NO response over the years this plugin was being completely ignored. 

Almost like this issue should have been addressed in the plugin itself so people didn't waste their time setting up the plugin only to be rejected at the last second.
