### ISSUE TITLE
Video Cover Disappear in 1 hour

### ISSUE THREAD

**Issue by pippo-c-l** [Automattic/fb-instant-articles#979]
## Steps required to reproduce the problem

1. Write and publish a post
2. Change manually post in Instant Articles - Production Articles with ```
<video>
<source src="link here" type="video/mp4" />
</video>
```
to remplace image cover with video cover
3. Save and Publish it

## Expected Result

Video Cover works very good but it disappear in 30 minutes, 1 hour

## Actual Result 

Video cover disappear

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.1.1
* WordPress version: 4.9.8
* PHP version: 7.2

Without the above information we are not able to debug the issue and will close it.

**Comment by Michaelovich** [comment]
I'am sorry this is not helping with your topic but I'am trying to use video covers instead of images on my website. Could you explain to me how to do this?
