### ISSUE TITLE
PHP Fatal error:  Cannot redeclare admin_notice__scrape_invalidation_failed()

### ISSUE THREAD

**Issue by abdusfauzi** [Automattic/fb-instant-articles#981]
## Steps required to reproduce the problem

1. Install plugin
2. Setup plugin
3. Select and Edit multiple post, press save.

## Expected Result
Nothing. Success message.

## Actual Result 
PHP Fatal error:  Cannot redeclare admin_notice__scrape_invalidation_failed() (previously declared in /home/vocket/thevocket.com/web/app/plugins/fb-instant-articles/facebook-instant-articles.php:525)
## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.1.1
* WordPress version: 4.9.8
* PHP version: 7.2

Without the above information we are not able to debug the issue and will close it.

**Comment by hengsoheak** [comment]
I also meet this error or this cause happen from version of php 7.3

`2019/09/08 06:02:44 [error] 10996#10996: *121667 FastCGI sent in stderr: "PHP message: PHP Warning:  A non-numeric value encountered in /var/www/html/camboland.com/wp-content/plugins/cactus-rating/cactus-rating.php on line 331PHP message: PHP Warning:  A non-numeric value encountered in /var/www/html/camboland.com/wp-content/plugins/cactus-rating/cactus-rating.php on line 331PHP message: PHP Warning:  A non-numeric value encountered in /var/www/html/camboland.com/wp-content/plugins/cactus-rating/cactus-rating.php on line 331PHP message: PHP Fatal error:  Cannot redeclare admin_notice__scrape_invalidation_failed() (previously declared in fb-instant-articles/facebook-instant-articles.php:492) in wp-content/plugins/fb-instant-articles/facebook-instant-articles.php on line 490" while reading response header from upstream, client: 141.101.107.148, server: camboland.com, request: "POST /wp-admin/post.php?post=6396&action=edit&meta-box-loader=1&meta-box-loader-nonce=988d218e86&_locale=user HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "www.camboland.com", referrer: "post.php?post=6396&action=edit"
`

**Comment by GaryJones** [comment]
The `admin_notice__scrape_invalidation_failed()` function (and others) are nested inside other functions, which is a bad idea for exactly this reason. The parent function is [hooked](https://github.com/Automattic/fb-instant-articles/blob/b8a0d4e44dc26578234e32d281b5560256abf5f3/facebook-instant-articles.php#L533) to `post_updated`, so if that hook runs twice (perhaps for different posts), then the inner functions are attempted to be defined twice.

**Comment by brysont** [comment]
For what it's worth... bulk-updating posts is all it takes to trigger this error.

`if (!function_exists('admin_notice__scrape_invalidation_failed')) {}`

Wrapped that function with that and the next (success) as well. Un-nesting those functions is definitely the long-term solution, but this at least keeps the plugin from breaking until the code is refactored.

Plugin version: 4.2.1 - 5
PHP version: 7.4
WP version: 6.0.1 - 6.0.3
