### ISSUE TITLE
Instant Article video covers not displaying on pages on ios12?

### ISSUE THREAD

**Issue by samichamoun** [Automattic/fb-instant-articles#985]
## Steps required to reproduce the problem

1. Setup a video link cover - https://developers.facebook.com/docs/instant-articles/design/videolink/
2. Post to a page.
3. View the post on the page from the FB app.

## Expected Result
On the page's timeline the video thumbnail should start playing. This was working on ios11.

## Actual Result 
The featured image displays instead of the video. However, once you click on the article and are viewing the instant article you can see the video thumbnail playing at the top of the page. Seems like it just isn't being picked up on the newsfeed and page timelines.

## Version Info
Using latest versions of everything, and ios12.

**Comment by kkszysiu** [comment]
Could be this? https://developers.facebook.com/support/bugs/250253175687554/

**Comment by besitruck** [comment]
all version not working  Video Link Cover
