### ISSUE TITLE
How to disable auto publishing Instant article?

### ISSUE THREAD

**Issue by duckyoumate** [Automattic/fb-instant-articles#988]
I don't have any "Production RSS Feed" but still, my old instant articles are being fetched and are getting "Live" automatically. We are already banned two times by facebook because some of our articles are NSFW, so we badly need control over the articles, which should be published and which should not.

**Is there any way to stop auto publishing on old instant articles?**
**Also, is there any way to disable IA on a specific post?**

Please help!

**Comment by royling96** [comment]
Try turning on Development Mode in WP Instant Articles settings under Publishing Settings.
