### ISSUE TITLE
Instant articles not converting in facebook page

### ISSUE THREAD

**Issue by damonsomu** [Automattic/fb-instant-articles#994]
We are using WordPress CMS and using the official plugin for instant articles. The issue is with our page Sambad( https://www.facebook.com/sambadofficial ). Everything was working fine before two months and the instant articles were getting published to the production perfectly.

We are approved for Instant articles(screenshot attached) but after sharing the article on Facebook its not getting converted to Instant articles. We have noticed a **Something went wrong** error in Production RSS Feed section of instant articles configuration page. But as we are using CMS plugin we are not bound to provide production RSS feed there as per our knowledge.

**404 error in production RSS feed section**
![image](https://user-images.githubusercontent.com/14832570/48600488-0d27a880-e992-11e8-9220-eb77e7ce85f3.png)

**Review screenshot**
![image](https://user-images.githubusercontent.com/14832570/48600512-24ff2c80-e992-11e8-8bf1-a33c367557da.png)

**Fixes We tried:**
1. Added the instant article production RSS feed link(http://sambad.in/feed/instant-articles) in production RSS feed in Facebook instant article settings. But it was showing 404 error even we waited for many days.
2. Directly pasting the Instant article markup using production article create button.
3. Switched the style of instant article to default.

None of the above fixes worked for us. The transform rules and details are given below. Kindly help to fix the issue.

## Transform Result 
**SOURCE MARKUP:**

`<p>ରଣପୁର: ରଣପୁର ଥାନା ଅନ୍ତର୍ଗତ ନରସିଂହପୁର ଅଞ୍ଚଳରେ ଏକ ଅଭାବନୀୟ ଘଟଣା ଘଟିଯାଇଛି। ଏହି ଗାଁର ଜଣେ ଦଶମ ଶ୍ରେଣୀ ଛାତ୍ରୀ ଟିଉସନ୍‌ରୁ ଫେରୁଥିବା ‌ବେଳେ ବାଟରେ କିଛି ଯୁବକ ତାଙ୍କୁ ଟେକି ନେଇ ଦୁଷ୍କର୍ମ ଉଦ୍ୟମ କରିଥିବା ଅଭିଯୋଗ ହୋଇଛି। ଅଭିଯୋଗ ମୁତାବକ, ହରିଆ ସାହୁ (ଛଦ୍ମ ନାମ)ଙ୍କ ଝିଅ ରୀତା (ଛଦ୍ମ ନାମ, ୧୫) ସବୁଦିନ ଭଳି ଗତ ସୋମବାର ଦିନ ସ୍କୁଲ୍‌ରେ ହେଉଥିବା ଟିଉସନରୁ ୨ ଜଣ ସାଙ୍ଗଙ୍କ ସହ ଘରକୁ ଫେରୁଥିଲେ। କିନ୍ତୁ ଅନ୍ୟ ୨ ଜଣ ସାଙ୍ଗ ଦୋକାନକୁ କିଛି କିଣିବାକୁ ଯାଇଥିଲେ। ରୀତା ରାସ୍ତାକଡ଼ରେ ଠିଆ ହୋଇଥିବା ବେଳେ ନରସିଂହପୁର ଗାଁର ସୁର ସାମନ୍ତଙ୍କ ପୁଅ ଲିଙ୍ଗରାଜ ସାମନ୍ତ, ପତିତପାବନ ସାମନ୍ତଙ୍କ ପୁଅ ତିରେନ୍ଦ୍ର ସାମନ୍ତ, ବ୍ରଜ ବଳିୟାର ସିଂହଙ୍କ ପୁଅ ସୁବ୍ରତ ବଳିୟାରସିଂହ, ନାରାୟଣ ଜେନାଙ୍କ ପୁଅ ମନୋରଞ୍ଜନ ଜେନା ଆଦି ଯୁବକମାନେ ଆସି ରୀତାଙ୍କ ନାକରେ କିଛି ଶୁଙ୍ଘାଇ ଦେଇଥିଲେ। ତେବେ ସେମାନେ ଟେକି ନେବା ସମୟରେ ରୀତା ବେହୋସ ହୋଇଯାଇଥିଲେ। ଦୀର୍ଘ ସମୟ ଧରି ରୀତା ଘରକୁ ନ ଫେରିବାରୁ ବହୁ ଖୋଜାଖୋଜି କରି ନିରାଶ ହେବା ପରେ ଶେଷରେ ଗାଁର ହରିଜନ ସାହି ବାରି ତଳେ ଥିବା ଏକ କୂଅ ନିକଟରେ ରୀତା ପଡ଼ିଥିବା ଦେଖି ଘର ଲୋ‌କେ ତାଙ୍କୁ ଉଦ୍ଧାର କରିଥିଲେ। ପରେ ରୀତାଙ୍କ ଚେତା ଫେରିଥିଲା। ଏ ନେଇ ଘର ଲୋକଙ୍କୁ ‌ସେ ଜଣାଇଥିଲେ। ଘଟଣାର ମୀମାଂଶା କରିବା ପାଇଁ ଭଦ୍ରଲୋକ ଓ ଗାଁ ସଭାପତିଙ୍କ ଜରିଆରେ ଉଭୟ ପକ୍ଷରୁ ଆଲୋଚନା ହୋଇଥିଲେ ହେଁ ଭୟରେ ଅଭିଯୁକ୍ତମାନେ ଗାଁରୁ କେଉଁ ଆଡ଼େ ପଳାଇ ଯାଇଛନ୍ତି। ଏ ନେଇ ଗ୍ରାମରେ ବୈଠକ ବସିଥିଲେ ମଧ୍ୟ କୌଣସି ସମାଧାନ ସୂତ୍ର ନ ବାହାରିବାରୁ ପୀଡ଼ିତାଙ୍କ ପରିବାର ଲୋକେ ଥାନାରେ ଏକ ଲିଖିତ ଅଭିଯୋଗ କରିଥିବା ଜଣାଯାଇଛି। ଅଭିଯୋଗ ପାଇ ପୁଲିସ୍‌ ତଦନ୍ତ କରୁଥିବା ଜଣାପଡ଼ିଛି।</p>`

**TRANSFORMED MARKUP:**

```
<html>
  <head>
    <link rel="canonical" href="http://sambad.in/district/nayagarh/minor-girl-rapecase-at-police-station-247619/"/>
    <meta charset="utf-8"/>
    <meta property="op:generator" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:version" content="1.9.2"/>
    <meta property="op:generator:application" content="facebook-instant-articles-wp"/>
    <meta property="op:generator:application:version" content="4.1.1"/>
    <meta property="op:generator:transformer" content="facebook-instant-articles-sdk-php"/>
    <meta property="op:generator:transformer:version" content="1.9.2"/>
    <meta property="op:markup_version" content="v1.0"/>
    <meta property="fb:use_automatic_ad_placement" content="enable=true ad_density=default"/>
    <meta property="fb:article_style" content="default"/>
  </head>
  <body>
    <article>
      <header>
        <figure>
          <img src="http://sambad.in/wp-content/uploads/2018/11/kidnapped.jpg"/>
        </figure>
        <h1>ନାବାଳିକାଙ୍କୁ ଦୁଷ୍କର୍ମ, ଥାନାରେ ଅଭିଯୋଗ</h1>
        <time class="op-published" datetime="2018-11-16T10:49:06+05:30">November 16th, 10:49am</time>
        <time class="op-modified" datetime="2018-11-16T10:49:06+05:30">November 16th, 10:49am</time>
        <address><a href="http://sambad.in">Rabi Narayan</a></address>
        <figure class="op-ad">
          <iframe src="https://www.facebook.com/adnw_request?placement=165646487318462_165646500651794&adtype=banner300x250" width="300" height="250"></iframe>
        </figure>
      </header>
      <p>ରଣପୁର: ରଣପୁର ଥାନା ଅନ୍ତର୍ଗତ ନରସିଂହପୁର ଅଞ୍ଚଳରେ ଏକ ଅଭାବନୀୟ ଘଟଣା ଘଟିଯାଇଛି। ଏହି ଗାଁର ଜଣେ ଦଶମ ଶ୍ରେଣୀ ଛାତ୍ରୀ ଟିଉସନ୍‌ରୁ ଫେରୁଥିବା ‌ବେଳେ ବାଟରେ କିଛି ଯୁବକ ତାଙ୍କୁ ଟେକି ନେଇ ଦୁଷ୍କର୍ମ ଉଦ୍ୟମ କରିଥିବା ଅଭିଯୋଗ ହୋଇଛି। ଅଭିଯୋଗ ମୁତାବକ, ହରିଆ ସାହୁ (ଛଦ୍ମ ନାମ)ଙ୍କ ଝିଅ ରୀତା (ଛଦ୍ମ ନାମ, ୧୫) ସବୁଦିନ ଭଳି ଗତ ସୋମବାର ଦିନ ସ୍କୁଲ୍‌ରେ ହେଉଥିବା ଟିଉସନରୁ ୨ ଜଣ ସାଙ୍ଗଙ୍କ ସହ ଘରକୁ ଫେରୁଥିଲେ। କିନ୍ତୁ ଅନ୍ୟ ୨ ଜଣ ସାଙ୍ଗ ଦୋକାନକୁ କିଛି କିଣିବାକୁ ଯାଇଥିଲେ। ରୀତା ରାସ୍ତାକଡ଼ରେ ଠିଆ ହୋଇଥିବା ବେଳେ ନରସିଂହପୁର ଗାଁର ସୁର ସାମନ୍ତଙ୍କ ପୁଅ ଲିଙ୍ଗରାଜ ସାମନ୍ତ, ପତିତପାବନ ସାମନ୍ତଙ୍କ ପୁଅ ତିରେନ୍ଦ୍ର ସାମନ୍ତ, ବ୍ରଜ ବଳିୟାର ସିଂହଙ୍କ ପୁଅ ସୁବ୍ରତ ବଳିୟାରସିଂହ, ନାରାୟଣ ଜେନାଙ୍କ ପୁଅ ମନୋରଞ୍ଜନ ଜେନା ଆଦି ଯୁବକମାନେ ଆସି ରୀତାଙ୍କ ନାକରେ କିଛି ଶୁଙ୍ଘାଇ ଦେଇଥିଲେ। ତେବେ ସେମାନେ ଟେକି ନେବା ସମୟରେ ରୀତା ବେହୋସ ହୋଇଯାଇଥିଲେ। ଦୀର୍ଘ ସମୟ ଧରି ରୀତା ଘରକୁ ନ ଫେରିବାରୁ ବହୁ ଖୋଜାଖୋଜି କରି ନିରାଶ ହେବା ପରେ ଶେଷରେ ଗାଁର ହରିଜନ ସାହି ବାରି ତଳେ ଥିବା ଏକ କୂଅ ନିକଟରେ ରୀତା ପଡ଼ିଥିବା ଦେଖି ଘର ଲୋ‌କେ ତାଙ୍କୁ ଉଦ୍ଧାର କରିଥିଲେ। ପରେ ରୀତାଙ୍କ ଚେତା ଫେରିଥିଲା। ଏ ନେଇ ଘର ଲୋକଙ୍କୁ ‌ସେ ଜଣାଇଥିଲେ। ଘଟଣାର ମୀମାଂଶା କରିବା ପାଇଁ ଭଦ୍ରଲୋକ ଓ ଗାଁ ସଭାପତିଙ୍କ ଜରିଆରେ ଉଭୟ ପକ୍ଷରୁ ଆଲୋଚନା ହୋଇଥିଲେ ହେଁ ଭୟରେ ଅଭିଯୁକ୍ତମାନେ ଗାଁରୁ କେଉଁ ଆଡ଼େ ପଳାଇ ଯାଇଛନ୍ତି। ଏ ନେଇ ଗ୍ରାମରେ ବୈଠକ ବସିଥିଲେ ମଧ୍ୟ କୌଣସି ସମାଧାନ ସୂତ୍ର ନ ବାହାରିବାରୁ ପୀଡ଼ିତାଙ୍କ ପରିବାର ଲୋକେ ଥାନାରେ ଏକ ଲିଖିତ ଅଭିଯୋଗ କରିଥିବା ଜଣାଯାଇଛି। ଅଭିଯୋଗ ପାଇ ପୁଲିସ୍‌ ତଦନ୍ତ କରୁଥିବା ଜଣାପଡ଼ିଛି।</p>
      <footer>
        <small>Sambad</small>
      </footer>
    </article>
  </body>
</html>
```

Website: http://sambad.in

## Version Info

* Plugin version: **4.1.1**
* WordPress version: **4.9.8**
* PHP version: **5.6.38**

**Comment by ankshvayt** [comment]
please contact me at https://brandnol.com
I'll fix it
