### ISSUE TITLE
This Article Isn't Eligible for Instant Articles

### ISSUE THREAD

**Issue by MyFacebookIA** [Automattic/fb-instant-articles#998]
## Steps required to reproduce the problem

all my 10 business pages have issues with Instant Articles since last week

in the production RSS feed section in FB Publishing tools i can see those errors as shown in screenshot
but if i go to list of production articles, they dont have any red marks

on some other pages i have suddenly a lot of red marks allthough nothing has changed
the articles are shown as unpublished, but for most of the users they still show as instant articles

i think facebook has a lot of bugs at the moment

i wrote many support requests to facebook , but zero usefull answers from them, just typical standard messages

anyone facing also issues since last week?

<img width="816" alt="screenshot 2018-12-10 at 07 23 05" src="https://user-images.githubusercontent.com/45792892/49806576-5f24d980-fd58-11e8-8fc7-70d6ffafe676.png">
<img width="758" alt="screenshot 2018-12-10 at 07 22 49" src="https://user-images.githubusercontent.com/45792892/49806578-5f24d980-fd58-11e8-87c8-66222166e77c.png">

## Version Info

Please state _exact_ versions, not _latest_ or _new_.

* Plugin version: 4.2.0
* WordPress version: 4.9.8  and also 5.0
* PHP version: 7

Without the above information we are not able to debug the issue and will close it.

**Comment by VoiceOf1980** [comment]
Thanks For Sharing This Problem! I am Getting Same kinds Issue On My Dashboard Last Few Days ! 

**But Surprising is, Articles get Insights Also, And get Earnings..**

### Also i cross checked all of section but can’t see any error or violations any where. even fro page manager all articles are render correctly. but i can’t see from my Facebook id any articles on instant articles mood.
Also I checked On Magnetization Manager Here Earnings and impressions Are Okay. Production RSS Feed Is Warning free. Only Get Unpublished And Warnings on Production Articles!

Please Help me to Resolve this issue. What can i do for this warning,

**Comment by MyFacebookIA** [comment]
> Thanks For Sharing This Problem! I am Getting Same kinds Issue On My Dashboard Last Few Days !
> 
> **But Surprising is, Articles get Insights Also, And get Earnings..**
> 
> ### Also i cross checked all of section but can’t see any error or violations any where. even fro page manager all articles are render correctly. but i can’t see from my Facebook id any articles on instant articles mood.
> Also I checked On Magnetization Manager Here Earnings and impressions Are Okay. Production RSS Feed Is Warning free. Only Get Unpublished And Warnings on Production Articles!
> 
> Please Help me to Resolve this issue. What can i do for this warning,

which country are you located?

**Comment by VoiceOf1980** [comment]
@MyFacebookIA  Thanks For Response. 
Me From Bangladesh -

**Comment by MyFacebookIA** [comment]
> @MyFacebookIA Thanks For Response.
> Me From Bangladesh -

maybe its an issue with our fonts why their automatic IA check is reporting problems?

**Comment by rajbharath2k17** [comment]
i have same issue for my new account. how can i solve. anyone please suggest.
thanks you

**Comment by vietnguyen09** [comment]
I have this issue too, does anyone have a solution? Please help

**Comment by terrapop** [comment]
Same problem here. Every article on new push via API gets the following error:

"General Errors: This Article Isn't Eligible for Instant Articles: This article doesn't meet the Content Guidelines for Monetization and will be published as a mobile website link instead of as an Instant Article"

However, updating with the exact same content removes the error and the article is published correctly. Please fix this Facebook!

**Comment by terrapop** [comment]
Update: It seems the error also disappears after some minutes automatically (even without the update). Looks like FB is giving a false error message until they checked the article for eligibility. Please fix this in the backend.

**Comment by PoeNedge** [comment]
Also getting this: You must fix the errors noted before your article can be published.

Although it's showing no errors. How frustrating is this. Please fix!
